[pytest]
testpaths = tests
addopts = --strict-markers -v -ra --tb=short
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    # Temporarily ignore the annoying connection cancel warning until we refactor the db session fixture
    ignore:coroutine 'Connection._cancel' was never awaited:RuntimeWarning
markers =
    integration: mark test as requiring external services or full DB
    e2e: mark test as an end-to-end test (slow)
