from __future__ import annotations

BLOCK_SIGNATURES = {
    "phrases": [
        "access denied",
        "access to this page has been denied",
        "robot or human",
        "are you a robot",
        "are you human",
        "please verify you are a human",
        "verify you are human",
        "complete the security check",
        "please complete the captcha",
        "enable javascript to view",
        "enable javascript and cookies",
        "you have been blocked",
        "this request was blocked",
        "sorry, you have been blocked",
        "checking your browser",
        "checking if the site connection is secure",
        "just a moment",
        "attention required",
        "pardon our interruption",
        "please turn javascript on",
        "why do i have to complete a captcha",
    ],
    "active_provider_markers": [
        {"marker": "px-captcha", "provider": "perimeterx"},
        {"marker": "cf-challenge", "provider": "cloudflare"},
        {"marker": "cf-browser-verification", "provider": "cloudflare"},
        {"marker": "dd-modal", "provider": "datadome"},
        {"marker": "incapsula", "provider": "incapsula"},
        {"marker": "distil", "provider": "distil"},
        {"marker": "shape security", "provider": "shape security"},
        {"marker": "arkose", "provider": "arkose"},
    ],
    "cdn_provider_markers": [
        {"marker": "perimeterx", "provider": "perimeterx"},
        {"marker": "cloudflare", "provider": "cloudflare"},
        {"marker": "akamai", "provider": "akamai"},
        {"marker": "akamaized", "provider": "akamai"},
        {"marker": "datadome", "provider": "datadome"},
        {"marker": "kasada", "provider": "kasada"},
    ],
    "provider_markers": [
        "perimeterx",
        "px-captcha",
        "cloudflare",
        "cf-challenge",
        "cf-browser-verification",
        "akamai",
        "akamaized",
        "datadome",
        "dd-modal",
        "kasada",
        "incapsula",
        "distil",
        "shape security",
        "hcaptcha",
        "recaptcha",
        "g-recaptcha",
        "funcaptcha",
        "arkose",
    ],
    "browser_challenge_strong_markers": {
        "captcha": "captcha",
        "verify you are human": "verification_text",
        "checking your browser": "browser_check",
        "cf-browser-verification": "cloudflare_verification",
        "challenge-platform": "challenge_platform",
        "just a moment": "interstitial_text",
        "access denied": "access_denied",
        "powered and protected by akamai": "akamai_banner",
        "datadome": "datadome_marker",
    },
    "browser_challenge_weak_markers": {
        "one more step": "generic_interstitial",
        "oops!! something went wrong": "generic_error_text",
        "error page": "error_page_text",
    },
    "title_regexes": [
        r"access\s+denied",
        r"robot\s+or\s+human",
        r"just\s+a\s+moment",
        r"attention\s+required",
        r"you\s+have\s+been\s+blocked",
        r"security\s+check",
        r"pardon\s+our\s+interruption",
    ],
}
