from __future__ import annotations

import json

from app.services.config.browser_fingerprint_profiles import (
    FONT_ALLOWLIST_BY_PLATFORM,
    WEBGL_PROFILE_BY_PLATFORM,
)


def _runtime_settings():
    from app.services.config.runtime_settings import crawler_runtime_settings

    return crawler_runtime_settings


def build_chrome_runtime_init_script(*, chrome_runtime_version: str) -> str:
    return "\n".join(
        [
            "(() => {",
            f"  const chromeRuntimeVersion = {chrome_runtime_version!r};",
            "  globalThis.chrome = globalThis.chrome || {};",
            "  if (typeof window !== 'undefined') { window.chrome = window.chrome || globalThis.chrome; }",
            "  const chromeRoot = globalThis.chrome;",
            "  const buildEvent = () => ({ addListener() {}, addRules() {}, getRules() { return []; }, hasListener() { return false; }, hasListeners() { return false; }, removeListener() {}, removeRules() {} });",
            "  const buildPort = () => ({ name: '', sender: undefined, disconnect() {}, onDisconnect: buildEvent(), onMessage: buildEvent(), postMessage() {} });",
            "  const runtime = chromeRoot.runtime && typeof chromeRoot.runtime === 'object' ? chromeRoot.runtime : {};",
            "  const extensionId = typeof runtime.id === 'string' && runtime.id ? runtime.id : '';",
            "  const assignIfMissing = (key, value) => { if (!(key in runtime)) { runtime[key] = value; } };",
            "  assignIfMissing('OnInstalledReason', { CHROME_UPDATE: 'chrome_update', INSTALL: 'install', SHARED_MODULE_UPDATE: 'shared_module_update', UPDATE: 'update' });",
            "  assignIfMissing('OnRestartRequiredReason', { APP_UPDATE: 'app_update', OS_UPDATE: 'os_update', PERIODIC: 'periodic' });",
            "  assignIfMissing('PlatformArch', { ARM: 'arm', ARM64: 'arm64', MIPS: 'mips', MIPS64: 'mips64', X86_32: 'x86-32', X86_64: 'x86-64' });",
            "  assignIfMissing('PlatformNaclArch', { ARM: 'arm', MIPS: 'mips', MIPS64: 'mips64', X86_32: 'x86-32', X86_64: 'x86-64' });",
            "  assignIfMissing('PlatformOs', { ANDROID: 'android', CROS: 'cros', LINUX: 'linux', MAC: 'mac', OPENBSD: 'openbsd', WIN: 'win' });",
            "  assignIfMissing('RequestUpdateCheckStatus', { NO_UPDATE: 'no_update', THROTTLED: 'throttled', UPDATE_AVAILABLE: 'update_available' });",
            "  assignIfMissing('connect', () => buildPort());",
            "  assignIfMissing('getManifest', () => undefined);",
            "  assignIfMissing('getURL', (path = '') => extensionId ? `chrome-extension://${extensionId}/${String(path || '').replace(/^\\/+/, '')}` : '');",
            "  assignIfMissing('id', undefined);",
            "  assignIfMissing('onConnect', buildEvent());",
            "  assignIfMissing('onInstalled', buildEvent());",
            "  assignIfMissing('onMessage', buildEvent());",
            "  assignIfMissing('onMessageExternal', buildEvent());",
            "  assignIfMissing('onRestartRequired', buildEvent());",
            "  assignIfMissing('onStartup', buildEvent());",
            "  assignIfMissing('onSuspend', buildEvent());",
            "  assignIfMissing('requestUpdateCheck', (callback) => { const status = 'no_update'; if (typeof callback === 'function') { queueMicrotask(() => callback(status)); } return Promise.resolve(status); });",
            "  assignIfMissing('sendMessage', (...args) => { const callback = args.find((value) => typeof value === 'function'); if (callback) { queueMicrotask(() => callback()); } return Promise.resolve(); });",
            "  assignIfMissing('getPlatformInfo', (callback) => { const info = { os: 'win', arch: 'x86-64', nacl_arch: 'x86-64' }; if (typeof callback === 'function') { queueMicrotask(() => callback(info)); } return Promise.resolve(info); });",
            "  const navigationEntry = () => {",
            "    try {",
            "      const entries = globalThis.performance && typeof globalThis.performance.getEntriesByType === 'function' ? globalThis.performance.getEntriesByType('navigation') : [];",
            "      return Array.isArray(entries) && entries.length ? entries[0] : null;",
            "    } catch (_) {",
            "      return null;",
            "    }",
            "  };",
            "  runtime.csi = runtime.csi || (() => {",
            "    const timing = globalThis.performance && globalThis.performance.timing ? globalThis.performance.timing : null;",
            "    const pageT = timing ? Math.max(1, Date.now() - Number(timing.navigationStart || Date.now())) : 320;",
            "    return { onloadT: Math.max(1, pageT), pageT: Math.max(1, pageT), startE: timing ? Number(timing.navigationStart || Date.now()) : Date.now(), tran: 15 };",
            "  });",
            "  runtime.loadTimes = runtime.loadTimes || (() => {",
            "    const timing = globalThis.performance && globalThis.performance.timing ? globalThis.performance.timing : null;",
            "    const nav = navigationEntry();",
            "    const requestTime = timing ? Number(timing.navigationStart || Date.now()) / 1000 : Date.now() / 1000;",
            "    const finishDocumentLoadTime = nav && Number.isFinite(nav.domContentLoadedEventEnd) ? Math.max(0.2, Number(nav.domContentLoadedEventEnd) / 1000) : 0.275;",
            "    const finishLoadTime = nav && Number.isFinite(nav.loadEventEnd) ? Math.max(finishDocumentLoadTime, Number(nav.loadEventEnd) / 1000) : 0.395;",
            "    const firstPaintTime = nav && Number.isFinite(nav.responseEnd) ? Math.max(0.12, Number(nav.responseEnd) / 1000) : 0.14;",
            "    return {",
            "      commitLoadTime: firstPaintTime,",
            "      connectionInfo: 'h2',",
            "      finishDocumentLoadTime,",
            "      finishLoadTime,",
            "      firstPaintAfterLoadTime: 0,",
            "      firstPaintTime,",
            "      navigationType: 'Other',",
            "      npnNegotiatedProtocol: 'h2',",
            "      requestTime,",
            "      startLoadTime: requestTime,",
            "      wasAlternateProtocolAvailable: false,",
            "      wasFetchedViaSpdy: true,",
            "      wasNpnNegotiated: true,",
            "    };",
            "  });",
            "  try { Object.defineProperty(chromeRoot, 'runtime', { value: runtime, enumerable: true, configurable: true, writable: true }); } catch (_) { chromeRoot.runtime = runtime; }",
            "})();",
        ]
    )


def build_audio_fingerprint_init_script(*, audio_seed: int) -> str:
    return "\n".join(
        [
            "(() => {",
            f"  const audioSeed = {int(audio_seed)};",
            "  const wrapMethod = (target, key, builder) => { if (!target) { return; } const nativeMethod = target[key]; if (typeof nativeMethod !== 'function' || nativeMethod.__crawlerWrapped) { return; } const wrapped = builder(nativeMethod); try { Object.defineProperty(wrapped, '__crawlerWrapped', { value: true }); } catch (_) {} try { target[key] = wrapped; } catch (_) {} };",
            "  const fillFloatSpectrum = (array) => { for (let index = 0; index < array.length; index += 1) { array[index] = -72 + ((audioSeed + index * 13) % 36) * 0.85; } };",
            "  const fillFloatWaveform = (array) => { for (let index = 0; index < array.length; index += 1) { array[index] = Math.max(-1, Math.min(1, Math.sin((audioSeed + index * 5) / 13) * 0.125)); } };",
            "  const fillByteWaveform = (array) => { for (let index = 0; index < array.length; index += 1) { array[index] = 96 + ((audioSeed + index * 9) % 64); } };",
            "  const patchAnalyserTarget = (target) => {",
            "    wrapMethod(target, 'getFloatFrequencyData', (nativeMethod) => function getFloatFrequencyData(array) { nativeMethod.call(this, array); let hasFiniteValue = false; for (let index = 0; index < array.length; index += 1) { if (Number.isFinite(array[index])) { hasFiniteValue = true; array[index] += ((((audioSeed + index * 11) % 9) - 4) / 5000); } } if (!hasFiniteValue) { fillFloatSpectrum(array); } });",
            "    wrapMethod(target, 'getByteFrequencyData', (nativeMethod) => function getByteFrequencyData(array) { nativeMethod.call(this, array); let hasSignal = false; for (let index = 0; index < array.length; index += 1) { if ((array[index] || 0) > 0) { hasSignal = true; array[index] = Math.max(0, Math.min(255, array[index] + (((audioSeed + index * 5) % 3) - 1))); } } if (!hasSignal) { for (let index = 0; index < array.length; index += 1) { array[index] = 32 + ((audioSeed + index * 7) % 64); } } });",
            "    wrapMethod(target, 'getFloatTimeDomainData', (nativeMethod) => function getFloatTimeDomainData(array) { nativeMethod.call(this, array); let hasSignal = false; for (let index = 0; index < array.length; index += 1) { const value = Number(array[index] || 0); if (Math.abs(value) > 0.0001) { hasSignal = true; array[index] = Math.max(-1, Math.min(1, value + ((((audioSeed + index * 3) % 7) - 3) / 4096))); } } if (!hasSignal) { fillFloatWaveform(array); } });",
            "    wrapMethod(target, 'getByteTimeDomainData', (nativeMethod) => function getByteTimeDomainData(array) { nativeMethod.call(this, array); let hasSignal = false; for (let index = 0; index < array.length; index += 1) { const value = Number(array[index] || 0); if (value !== 0 && value !== 128) { hasSignal = true; array[index] = Math.max(0, Math.min(255, value + (((audioSeed + index * 7) % 5) - 2))); } } if (!hasSignal) { fillByteWaveform(array); } });",
            "  };",
            "  const patchAudioContextInstance = (context) => {",
            "    if (!context || typeof context !== 'object') {",
            "      return context;",
            "    }",
            "    wrapMethod(context, 'createAnalyser', (nativeMethod) => function createAnalyser(...args) { const analyser = nativeMethod.apply(this, args); if (analyser && typeof analyser === 'object') { patchAnalyserTarget(analyser); } return analyser; });",
            "    return context;",
            "  };",
            "  const wrapContextConstructor = (globalKey) => {",
            "    const NativeCtor = globalThis[globalKey];",
            "    if (typeof NativeCtor !== 'function' || NativeCtor.__crawlerWrappedCtor) {",
            "      return;",
            "    }",
            "    const WrappedCtor = new Proxy(NativeCtor, {",
            "      construct(target, args, newTarget) {",
            "        return patchAudioContextInstance(Reflect.construct(target, args, newTarget));",
            "      },",
            "    });",
            "    try { Object.defineProperty(WrappedCtor, '__crawlerWrappedCtor', { value: true }); } catch (_) {}",
            "    try { Object.defineProperty(WrappedCtor, 'prototype', { value: NativeCtor.prototype }); } catch (_) {}",
            "    try { Object.defineProperty(WrappedCtor, 'name', { value: NativeCtor.name, configurable: true }); } catch (_) {}",
            "    try { Object.defineProperty(WrappedCtor, 'toString', { value: NativeCtor.toString.bind(NativeCtor), configurable: true }); } catch (_) {}",
            "    try { globalThis[globalKey] = WrappedCtor; } catch (_) {}",
            "  };",
            "  wrapMethod(typeof AudioBuffer !== 'undefined' ? AudioBuffer.prototype : undefined, 'getChannelData', (nativeMethod) => function getChannelData(channel) { const values = nativeMethod.call(this, channel); if (!values || typeof values.length !== 'number' || values.length === 0) { return values; } const stride = Math.max(1, Math.floor(values.length / 32)); const clone = typeof values.slice === 'function' ? values.slice(0) : new Float32Array(values); for (let index = 0; index < clone.length; index += stride) { clone[index] = Math.max(-1, Math.min(1, clone[index] + ((((audioSeed + Number(channel || 0) * 19 + index * 7) % 17) - 8) / 32768))); } return clone; });",
            "  if (typeof AnalyserNode !== 'undefined' && AnalyserNode.prototype) { patchAnalyserTarget(AnalyserNode.prototype); }",
            "  const contextCtors = [['AudioContext', globalThis.AudioContext], ['OfflineAudioContext', globalThis.OfflineAudioContext], ['webkitAudioContext', globalThis.webkitAudioContext]];",
            "  for (const [globalKey, ContextCtor] of contextCtors) {",
            "    if (!ContextCtor || !ContextCtor.prototype) { continue; }",
            "    wrapMethod(ContextCtor.prototype, 'createAnalyser', (nativeMethod) => function createAnalyser(...args) { const analyser = nativeMethod.apply(this, args); if (analyser && typeof analyser === 'object') { patchAnalyserTarget(analyser); } return analyser; });",
            "    wrapContextConstructor(globalKey);",
            "  }",
            "})();",
        ]
    )


def build_permissions_coherence_init_script(
    *,
    granted_permissions: tuple[str, ...],
) -> str:
    granted_set = {str(value).strip().lower() for value in granted_permissions if str(value).strip()}
    permission_defaults = {
        "notifications": _runtime_settings().browser_permission_notifications_state,
        "camera": _runtime_settings().browser_permission_camera_state,
        "microphone": _runtime_settings().browser_permission_microphone_state,
        "geolocation": _runtime_settings().browser_permission_geolocation_state,
    }
    permission_states = {
        name: ("granted" if name in granted_set else str(default))
        for name, default in permission_defaults.items()
    }
    media_devices = [
        {
            "deviceId": "",
            "groupId": "",
            "kind": "audioinput",
            "label": "Default Microphone" if permission_states["microphone"] == "granted" else "",
        },
        {
            "deviceId": "",
            "groupId": "",
            "kind": "audiooutput",
            "label": "Default Speakers",
        },
        {
            "deviceId": "",
            "groupId": "",
            "kind": "videoinput",
            "label": "Integrated Camera" if permission_states["camera"] == "granted" else "",
        },
    ]
    return "\n".join(
        [
            "(() => {",
            f"  const permissionStates = {json.dumps(permission_states, separators=(',', ':'))};",
            f"  const mediaDevicesPayload = {json.dumps(media_devices, separators=(',', ':'))};",
            "  const installDescriptor = (target, key, getter) => {",
            "    if (!target) {",
            "      return;",
            "    }",
            "    try {",
            "      Object.defineProperty(target, key, {",
            "        get: getter,",
            "        enumerable: false,",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "  };",
            "  const buildPermissionStatus = (state) => ({",
            "    state,",
            "    onchange: null,",
            "    addEventListener() {},",
            "    removeEventListener() {},",
            "    dispatchEvent() { return true; },",
            "  });",
            "  try {",
            "    if (typeof Notification !== 'undefined') {",
            "      installDescriptor(Notification, 'permission', () => permissionStates.notifications || 'prompt');",
            "    }",
            "  } catch (_) {}",
            "  try {",
            "    const nativeQuery = Navigator.prototype.permissions?.query || navigator.permissions?.query?.bind(navigator.permissions);",
            "    if (nativeQuery) {",
            "      const wrappedQuery = async function query(permissionDesc) {",
            "        const name = String(permissionDesc && permissionDesc.name || '').toLowerCase();",
            "        if (Object.prototype.hasOwnProperty.call(permissionStates, name)) {",
            "          return buildPermissionStatus(permissionStates[name]);",
            "        }",
            "        return nativeQuery.call(this, permissionDesc);",
            "      };",
            "      if (navigator.permissions) {",
            "        navigator.permissions.query = wrappedQuery.bind(navigator.permissions);",
            "      }",
            "      try {",
            "        installDescriptor(Permissions.prototype, 'query', () => wrappedQuery);",
            "      } catch (_) {}",
            "    }",
            "  } catch (_) {}",
            "  try {",
            "    if (typeof MediaDeviceInfo === 'undefined') {",
            "      globalThis.MediaDeviceInfo = class MediaDeviceInfo {};",
            "    }",
            "    if (typeof navigator !== 'undefined' && navigator.mediaDevices) {",
            "      navigator.mediaDevices.enumerateDevices = async () => mediaDevicesPayload.map((device) => ({ ...device }));",
            "    } else {",
            "      installDescriptor(Navigator.prototype, 'mediaDevices', () => ({",
            "        enumerateDevices: async () => mediaDevicesPayload.map((device) => ({ ...device })),",
            "        getSupportedConstraints: () => ({}),",
            "      }));",
            "    }",
            "  } catch (_) {}",
            "  try {",
            "    if (typeof NetworkInformation !== 'undefined') {",
            "      installDescriptor(NetworkInformation.prototype, 'downlinkMax', () => 10);",
            "    }",
            "  } catch (_) {}",
            "  try {",
            "    if (typeof ContentIndex === 'undefined') {",
            "      globalThis.ContentIndex = class ContentIndex {",
            "        async add() { return undefined; }",
            "        async delete() { return undefined; }",
            "        async getAll() { return []; }",
            "      };",
            "    }",
            "    if (typeof ServiceWorkerRegistration === 'undefined') {",
            "      globalThis.ServiceWorkerRegistration = class ServiceWorkerRegistration {};",
            "    }",
            "    installDescriptor(ServiceWorkerRegistration.prototype, 'contentIndex', () => new ContentIndex());",
            "  } catch (_) {}",
            "  try {",
            "    if (typeof ContactsManager === 'undefined') {",
            "      globalThis.ContactsManager = class ContactsManager {",
            "        async getProperties() { return ['name', 'email', 'tel', 'address', 'icon']; }",
            "        async select() { return []; }",
            "      };",
            "    }",
            "    installDescriptor(Navigator.prototype, 'contacts', () => new ContactsManager());",
            "  } catch (_) {}",
            "})();",
        ]
    )


def build_canvas_fingerprint_init_script(*, canvas_seed: int) -> str:
    return "\n".join(
        [
            "(() => {",
            f"  const canvasSeed = {int(canvas_seed)} >>> 0;",
            "  if (typeof CanvasRenderingContext2D === 'undefined' || typeof HTMLCanvasElement === 'undefined') { return; }",
            "  const nativeGetImageData = CanvasRenderingContext2D.prototype.getImageData;",
            "  const nativePutImageData = CanvasRenderingContext2D.prototype.putImageData;",
            "  const nativeToDataURL = HTMLCanvasElement.prototype.toDataURL;",
            "  const nativeToBlob = HTMLCanvasElement.prototype.toBlob;",
            "  const clampByte = (value) => Math.max(0, Math.min(255, value));",
            "  const cloneImageData = (ctx, imageData) => {",
            "    try { return new ImageData(new Uint8ClampedArray(imageData.data), imageData.width, imageData.height); }",
            "    catch (_) { const clone = ctx.createImageData(imageData.width, imageData.height); clone.data.set(imageData.data); return clone; }",
            "  };",
            "  const channelDelta = (pixelIndex, channelIndex) => {",
            "    const raw = ((canvasSeed + pixelIndex * 13 + channelIndex * 7) % 7) - 3;",
            "    return raw === 0 ? 1 : raw;",
            "  };",
            "  const applyCanvasNoise = (imageData) => {",
            "    const data = imageData && imageData.data;",
            "    if (!data || !data.length) { return imageData; }",
            "    for (let offset = 0; offset < data.length; offset += 4) {",
            "      const pixelIndex = offset / 4;",
            "      if (((pixelIndex + canvasSeed) % 4) !== 0) { continue; }",
            "      data[offset] = clampByte(data[offset] + channelDelta(pixelIndex, 0));",
            "      data[offset + 1] = clampByte(data[offset + 1] + channelDelta(pixelIndex, 1));",
            "      data[offset + 2] = clampByte(data[offset + 2] + channelDelta(pixelIndex, 2));",
            "    }",
            "    return imageData;",
            "  };",
            "  const buildNoisedCanvas = (sourceCanvas) => {",
            "    const width = Number(sourceCanvas && sourceCanvas.width || 0);",
            "    const height = Number(sourceCanvas && sourceCanvas.height || 0);",
            "    if (width <= 0 || height <= 0) { return sourceCanvas; }",
            "    const sourceCtx = sourceCanvas.getContext('2d');",
            "    if (!sourceCtx || typeof nativeGetImageData !== 'function' || typeof nativePutImageData !== 'function') { return sourceCanvas; }",
            "    try {",
            "      const raw = nativeGetImageData.call(sourceCtx, 0, 0, width, height);",
            "      const noised = applyCanvasNoise(cloneImageData(sourceCtx, raw));",
            "      const clone = document.createElement('canvas');",
            "      clone.width = width;",
            "      clone.height = height;",
            "      const cloneCtx = clone.getContext('2d');",
            "      if (!cloneCtx) { return sourceCanvas; }",
            "      nativePutImageData.call(cloneCtx, noised, 0, 0);",
            "      return clone;",
            "    } catch (_) {",
            "      return sourceCanvas;",
            "    }",
            "  };",
            "  CanvasRenderingContext2D.prototype.getImageData = function getImageData(...args) {",
            "    const imageData = nativeGetImageData.apply(this, args);",
            "    return applyCanvasNoise(cloneImageData(this, imageData));",
            "  };",
            "  HTMLCanvasElement.prototype.toDataURL = function toDataURL(...args) {",
            "    return nativeToDataURL.apply(buildNoisedCanvas(this), args);",
            "  };",
            "  if (typeof nativeToBlob === 'function') {",
            "    HTMLCanvasElement.prototype.toBlob = function toBlob(callback, ...args) {",
            "      return nativeToBlob.call(buildNoisedCanvas(this), callback, ...args);",
            "    };",
            "  }",
            "})();",
        ]
    )


def build_webgl_fingerprint_init_script(
    *,
    platform_label: str,
    is_mobile: bool,
    webgl_seed: int,
) -> str:
    profile_key = "mobile" if is_mobile else platform_label
    profile = dict(
        WEBGL_PROFILE_BY_PLATFORM.get(
            profile_key,
            WEBGL_PROFILE_BY_PLATFORM["Windows"],
        )
    )
    return "\n".join(
        [
            "(() => {",
            f"  const webglSeed = {int(webgl_seed)} >>> 0;",
            f"  const profile = {json.dumps(profile, separators=(',', ':'))};",
            "  const DEBUG_RENDERER_INFO = { UNMASKED_VENDOR_WEBGL: 37445, UNMASKED_RENDERER_WEBGL: 37446 };",
            "  const ANISO = { MAX_TEXTURE_MAX_ANISOTROPY_EXT: 34047 };",
            "  const LOSE_CONTEXT = { loseContext() {}, restoreContext() {} };",
            "  const cloneValue = (value) => {",
            "    if (Array.isArray(value)) { return value.slice(); }",
            "    if (value instanceof Int32Array) { return new Int32Array(value); }",
            "    if (value instanceof Float32Array) { return new Float32Array(value); }",
            "    return value;",
            "  };",
            "  const applyPixelNoise = (pixels) => {",
            "    if (!pixels || typeof pixels.length !== 'number') { return; }",
            "    const byteStep = pixels.BYTES_PER_ELEMENT === 1 ? 4 : Math.max(4, pixels.BYTES_PER_ELEMENT * 4);",
            "    for (let offset = 0; offset < pixels.length; offset += byteStep) {",
            "      const pixelIndex = Math.floor(offset / byteStep);",
            "      if (((pixelIndex + webglSeed) % 4) !== 0) { continue; }",
            "      for (let channel = 0; channel < 3 && offset + channel < pixels.length; channel += 1) {",
            "        const delta = ((webglSeed + pixelIndex * 17 + channel * 11) % 7) - 3 || 1;",
            "        if (pixels.BYTES_PER_ELEMENT === 1) { pixels[offset + channel] = Math.max(0, Math.min(255, pixels[offset + channel] + delta)); }",
            "        else { pixels[offset + channel] = pixels[offset + channel] + (delta / 1024); }",
            "      }",
            "    }",
            "  };",
            "  const parameterOverrides = new Map([",
            "    [7936, profile.vendor],",
            "    [7937, profile.renderer],",
            "    [7938, profile.version],",
            "    [35724, profile.shading_language_version],",
            "    [37445, profile.vendor],",
            "    [37446, profile.renderer],",
            "    [3379, profile.max_texture_size],",
            "    [34024, profile.max_renderbuffer_size],",
            "    [34076, profile.max_cube_map_texture_size],",
            "    [3386, new Int32Array(profile.max_viewport_dims)],",
            "    [34930, profile.max_texture_image_units],",
            "    [35661, profile.max_combined_texture_image_units],",
            "    [35660, profile.max_vertex_texture_image_units],",
            "    [34921, profile.max_vertex_attribs],",
            "    [36347, profile.max_vertex_uniform_vectors],",
            "    [36349, profile.max_fragment_uniform_vectors],",
            "    [33902, new Float32Array(profile.aliased_line_width_range)],",
            "    [33901, new Float32Array(profile.aliased_point_size_range)],",
            "    [34047, profile.max_anisotropy],",
            "  ]);",
            "  const precisionFormats = new Map([",
            "    [36336, { rangeMin: 127, rangeMax: 127, precision: 8 }],",
            "    [36337, { rangeMin: 127, rangeMax: 127, precision: 10 }],",
            "    [36338, { rangeMin: 127, rangeMax: 127, precision: 23 }],",
            "    [36339, { rangeMin: 31, rangeMax: 30, precision: 0 }],",
            "    [36340, { rangeMin: 31, rangeMax: 30, precision: 0 }],",
            "    [36341, { rangeMin: 31, rangeMax: 30, precision: 0 }],",
            "  ]);",
            "  const patchPrototype = (prototype) => {",
            "    if (!prototype) { return; }",
            "    const nativeGetParameter = prototype.getParameter;",
            "    const nativeGetSupportedExtensions = prototype.getSupportedExtensions;",
            "    const nativeGetExtension = prototype.getExtension;",
            "    const nativeGetShaderPrecisionFormat = prototype.getShaderPrecisionFormat;",
            "    const nativeReadPixels = prototype.readPixels;",
            "    if (typeof nativeGetParameter === 'function') {",
            "      prototype.getParameter = function getParameter(pname) {",
            "        if (parameterOverrides.has(pname)) { return cloneValue(parameterOverrides.get(pname)); }",
            "        return nativeGetParameter.call(this, pname);",
            "      };",
            "    }",
            "    if (typeof nativeGetSupportedExtensions === 'function') {",
            "      prototype.getSupportedExtensions = function getSupportedExtensions() {",
            "        return Array.from(profile.supported_extensions);",
            "      };",
            "    }",
            "    if (typeof nativeGetExtension === 'function') {",
            "      prototype.getExtension = function getExtension(name) {",
            "        const normalized = String(name || '').trim();",
            "        if (normalized === 'WEBGL_debug_renderer_info') { return DEBUG_RENDERER_INFO; }",
            "        if (normalized === 'EXT_texture_filter_anisotropic' || normalized === 'MOZ_EXT_texture_filter_anisotropic' || normalized === 'WEBKIT_EXT_texture_filter_anisotropic') { return ANISO; }",
            "        if (normalized === 'WEBGL_lose_context') { return LOSE_CONTEXT; }",
            "        if (!profile.supported_extensions.includes(normalized)) { return null; }",
            "        return nativeGetExtension.call(this, name) || {};",
            "      };",
            "    }",
            "    if (typeof nativeGetShaderPrecisionFormat === 'function') {",
            "      prototype.getShaderPrecisionFormat = function getShaderPrecisionFormat(shaderType, precisionType) {",
            "        if (precisionFormats.has(precisionType)) { return { ...precisionFormats.get(precisionType) }; }",
            "        return nativeGetShaderPrecisionFormat.call(this, shaderType, precisionType);",
            "      };",
            "    }",
            "    if (typeof nativeReadPixels === 'function') {",
            "      prototype.readPixels = function readPixels(...args) {",
            "        const result = nativeReadPixels.apply(this, args);",
            "        const pixels = [...args].reverse().find((value) => value && typeof value === 'object' && ArrayBuffer.isView(value));",
            "        applyPixelNoise(pixels);",
            "        return result;",
            "      };",
            "    }",
            "  };",
            "  patchPrototype(globalThis.WebGLRenderingContext && globalThis.WebGLRenderingContext.prototype);",
            "  patchPrototype(globalThis.WebGL2RenderingContext && globalThis.WebGL2RenderingContext.prototype);",
            "})();",
        ]
    )


def _font_profile_key(*, platform_label: str, is_mobile: bool) -> str:
    return "mobile" if is_mobile else platform_label


def build_font_surface_init_script(
    *,
    platform_label: str,
    is_mobile: bool,
) -> str:
    profile_key = _font_profile_key(
        platform_label=platform_label,
        is_mobile=is_mobile,
    )
    allowed_fonts = tuple(
        FONT_ALLOWLIST_BY_PLATFORM.get(
            profile_key,
            FONT_ALLOWLIST_BY_PLATFORM["Windows"],
        )
    )
    return "\n".join(
        [
            "(() => {",
            f"  const allowedFonts = new Set({json.dumps(list(allowed_fonts), separators=(',', ':'))});",
            "  const genericFonts = new Set(['serif', 'sans-serif', 'monospace', 'system-ui', 'cursive', 'fantasy', 'math', 'emoji', 'fangsong', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 'ui-rounded']);",
            "  const normalizeFontFamily = (value) => String(value || '').trim().replace(/^['\\\"]|['\\\"]$/g, '').trim().toLowerCase();",
            "  const extractFamilySegment = (value) => {",
            "    const raw = String(value || '').trim();",
            "    if (!raw) {",
            "      return raw;",
            "    }",
            "    const sizeMatch = raw.match(/(?:^|\\s)\\d+(?:\\.\\d+)?(?:px|pt|pc|em|rem|ex|ch|vh|vw|vmin|vmax|%)\\s*(?:\\/[^,\\s]+)?\\s*(.+)$/i);",
            "    return sizeMatch && sizeMatch[1] ? sizeMatch[1] : raw;",
            "  };",
            "  const sanitizeFamilies = (value) => {",
            "    const normalizedFamilies = extractFamilySegment(value).split(',').map(normalizeFontFamily).filter(Boolean);",
            "    const sanitized = [];",
            "    let fallbackGeneric = '';",
            "    for (const family of normalizedFamilies) {",
            "      if (genericFonts.has(family)) {",
            "        sanitized.push(family);",
            "        if (!fallbackGeneric) {",
            "          fallbackGeneric = family;",
            "        }",
            "        continue;",
            "      }",
            "      if (allowedFonts.has(family)) {",
            "        sanitized.push(family);",
            "      }",
            "    }",
            "    if (!fallbackGeneric) {",
            "      fallbackGeneric = 'sans-serif';",
            "    }",
            "    if (!sanitized.length) {",
            "      sanitized.push(fallbackGeneric);",
            "    }",
            "    if (!sanitized.some((family) => genericFonts.has(family))) {",
            "      sanitized.push(fallbackGeneric);",
            "    }",
            "    return sanitized;",
            "  };",
            "  const sanitizeFontFamilyValue = (value) => sanitizeFamilies(value).join(', ');",
            "  const sanitizeFontSpec = (fontSpec) => {",
            "    const raw = String(fontSpec || '').trim();",
            "    if (!raw) {",
            "      return raw;",
            "    }",
            "    const sizeMatch = raw.match(/(?:^|\\s)\\d+(?:\\.\\d+)?(?:px|pt|pc|em|rem|ex|ch|vh|vw|vmin|vmax|%)\\s*(?:\\/[^,\\s]+)?\\s*(.+)$/i);",
            "    if (!sizeMatch || !sizeMatch[1]) {",
            "      return sanitizeFontFamilyValue(raw);",
            "    }",
            "    const familySegment = sizeMatch[1];",
            "    const prefix = raw.slice(0, raw.length - familySegment.length);",
            "    return prefix + sanitizeFontFamilyValue(familySegment);",
            "  };",
            "  const rewriteStyleText = (value) => String(value || '')",
            "    .replace(/font-family\\s*:\\s*([^;]+)(;?)/gi, (_match, familyValue, suffix) => `font-family: ${sanitizeFontFamilyValue(familyValue)}${suffix || ''}`)",
            "    .replace(/(^|[;\\s])font\\s*:\\s*([^;]+)(;?)/gi, (_match, prefix, fontValue, suffix) => `${prefix}font: ${sanitizeFontSpec(fontValue)}${suffix || ''}`);",
            "  const installDescriptor = (target, key, getter) => {",
            "    if (!target) {",
            "      return;",
            "    }",
            "    try {",
            "      Object.defineProperty(target, key, {",
            "        get: getter,",
            "        enumerable: false,",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "  };",
            "  const patchStyleDescriptor = (key, sanitizer) => {",
            "    if (typeof CSSStyleDeclaration === 'undefined' || !CSSStyleDeclaration.prototype) {",
            "      return;",
            "    }",
            "    const descriptor = Object.getOwnPropertyDescriptor(CSSStyleDeclaration.prototype, key);",
            "    if (!descriptor || typeof descriptor.set !== 'function') {",
            "      return;",
            "    }",
            "    try {",
            "      Object.defineProperty(CSSStyleDeclaration.prototype, key, {",
            "        get() {",
            "          return descriptor.get ? descriptor.get.call(this) : '';",
            "        },",
            "        set(value) {",
            "          return descriptor.set.call(this, sanitizer(value));",
            "        },",
            "        enumerable: descriptor.enumerable,",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "  };",
            "  const patchCanvasFontDescriptor = (prototype) => {",
            "    if (!prototype) {",
            "      return;",
            "    }",
            "    const descriptor = Object.getOwnPropertyDescriptor(prototype, 'font');",
            "    if (!descriptor || typeof descriptor.set !== 'function') {",
            "      return;",
            "    }",
            "    try {",
            "      Object.defineProperty(prototype, 'font', {",
            "        get() {",
            "          return descriptor.get ? descriptor.get.call(this) : '';",
            "        },",
            "        set(value) {",
            "          return descriptor.set.call(this, sanitizeFontSpec(value));",
            "        },",
            "        enumerable: descriptor.enumerable,",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "  };",
            "  try {",
            "    if (typeof CSSStyleDeclaration !== 'undefined' && CSSStyleDeclaration.prototype && typeof CSSStyleDeclaration.prototype.setProperty === 'function') {",
            "      const nativeSetProperty = CSSStyleDeclaration.prototype.setProperty;",
            "      CSSStyleDeclaration.prototype.setProperty = function setProperty(name, value, priority) {",
            "        const normalizedName = String(name || '').trim().toLowerCase();",
            "        if (normalizedName === 'font-family') {",
            "          return nativeSetProperty.call(this, name, sanitizeFontFamilyValue(value), priority);",
            "        }",
            "        if (normalizedName === 'font') {",
            "          return nativeSetProperty.call(this, name, sanitizeFontSpec(value), priority);",
            "        }",
            "        return nativeSetProperty.call(this, name, value, priority);",
            "      };",
            "    }",
            "  } catch (_) {}",
            "  patchStyleDescriptor('fontFamily', sanitizeFontFamilyValue);",
            "  patchStyleDescriptor('font', sanitizeFontSpec);",
            "  try {",
            "    if (typeof Element !== 'undefined' && Element.prototype && typeof Element.prototype.setAttribute === 'function') {",
            "      const nativeSetAttribute = Element.prototype.setAttribute;",
            "      Element.prototype.setAttribute = function setAttribute(name, value) {",
            "        if (String(name || '').trim().toLowerCase() === 'style') {",
            "          return nativeSetAttribute.call(this, name, rewriteStyleText(value));",
            "        }",
            "        return nativeSetAttribute.call(this, name, value);",
            "      };",
            "    }",
            "  } catch (_) {}",
            "  patchCanvasFontDescriptor(globalThis.CanvasRenderingContext2D && globalThis.CanvasRenderingContext2D.prototype);",
            "  patchCanvasFontDescriptor(globalThis.OffscreenCanvasRenderingContext2D && globalThis.OffscreenCanvasRenderingContext2D.prototype);",
            "  try {",
            "    if (typeof FontFaceSet !== 'undefined' && FontFaceSet.prototype && typeof FontFaceSet.prototype.check === 'function') {",
            "      const nativeCheck = FontFaceSet.prototype.check;",
            "      FontFaceSet.prototype.check = function check(fontSpec, text) {",
            "        const families = sanitizeFamilies(fontSpec);",
            "        if (!families.length) {",
            "          return nativeCheck.call(this, fontSpec, text);",
            "        }",
            "        for (const family of families) {",
            "          if (genericFonts.has(family)) {",
            "            continue;",
            "          }",
            "          if (!allowedFonts.has(family)) {",
            "            return false;",
            "          }",
            "        }",
            "        return nativeCheck.call(this, sanitizeFontSpec(fontSpec), text);",
            "      };",
            "    }",
            "  } catch (_) {}",
            "  try {",
            "    if (typeof document !== 'undefined' && document.fonts) {",
            "      installDescriptor(document.fonts, 'ready', () => Promise.resolve(document.fonts));",
            "    }",
            "  } catch (_) {}",
            "})();",
        ]
    )


def build_navigator_coherence_init_script(
    *,
    platform_label: str,
    is_mobile: bool,
    viewport_width: int,
    viewport_height: int,
) -> str:
    connection_profile = {
        "effectiveType": _runtime_settings().browser_connection_effective_type,
        "downlink": float(_runtime_settings().browser_connection_downlink_mbps),
        "downlinkMax": float(
            _runtime_settings().browser_connection_downlink_max_mbps
        ),
        "rtt": int(_runtime_settings().browser_connection_rtt_ms),
        "saveData": bool(_runtime_settings().browser_connection_save_data),
        "type": str(_runtime_settings().browser_connection_type or "wifi"),
    }
    orientation_angle = 90 if int(viewport_width) > int(viewport_height) else 0
    orientation_type = (
        "landscape-primary"
        if int(viewport_width) > int(viewport_height)
        else "portrait-primary"
    )
    max_touch_points = (
        max(1, int(_runtime_settings().browser_mobile_max_touch_points))
        if is_mobile
        else 0
    )
    return "\n".join(
        [
            "(() => {",
            f"  const connectionProfile = {json.dumps(connection_profile, separators=(',', ':'))};",
            f"  const maxTouchPoints = {int(max_touch_points)};",
            f"  const orientationAngle = {int(orientation_angle)};",
            f"  const orientationType = {json.dumps(orientation_type)};",
            "  const installDescriptor = (target, key, getter) => {",
            "    if (!target) {",
            "      return;",
            "    }",
            "    try {",
            "      Object.defineProperty(target, key, {",
            "        get: getter,",
            "        enumerable: false,",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "  };",
            "  const connection = {",
            "    ...connectionProfile,",
            "    onchange: null,",
            "    addEventListener() {},",
            "    removeEventListener() {},",
            "    dispatchEvent() { return true; },",
            "  };",
            "  const keyboardLayoutEntries = [['Backquote', '`'], ['Digit1', '1'], ['KeyA', 'a'], ['Space', ' ']];",
            "  const buildKeyboard = () => {",
            "    const keyboard = {",
            "      getLayoutMap() { return Promise.resolve(new Map(keyboardLayoutEntries)); },",
            "      lock() { return Promise.resolve(); },",
            "      unlock() {},",
            "      addEventListener() {},",
            "      removeEventListener() {},",
            "      dispatchEvent() { return true; },",
            "    };",
            "    try {",
            "      if (typeof Keyboard !== 'undefined' && Keyboard.prototype) {",
            "        Object.setPrototypeOf(keyboard, Keyboard.prototype);",
            "      }",
            "    } catch (_) {}",
            "    return keyboard;",
            "  };",
            "  const buildMediaCapabilities = () => {",
            "    const normalizeMediaSupport = (config) => ({",
            "      supported: Boolean(config && typeof config === 'object'),",
            "      smooth: true,",
            "      powerEfficient: false,",
            "      keySystemAccess: null,",
            "      configuration: config && typeof config === 'object' ? config : undefined,",
            "    });",
            "    const mediaCapabilities = {",
            "      decodingInfo(config) { return Promise.resolve(normalizeMediaSupport(config)); },",
            "      encodingInfo(config) { return Promise.resolve(normalizeMediaSupport(config)); },",
            "    };",
            "    try {",
            "      if (typeof MediaCapabilities !== 'undefined' && MediaCapabilities.prototype) {",
            "        Object.setPrototypeOf(mediaCapabilities, MediaCapabilities.prototype);",
            "      }",
            "    } catch (_) {}",
            "    return mediaCapabilities;",
            "  };",
            "  const buildGpu = () => {",
            "    const gpu = {",
            "      wgslLanguageFeatures: new Set(),",
            "      requestAdapter() { return Promise.resolve(null); },",
            "      getPreferredCanvasFormat() { return 'bgra8unorm'; },",
            "    };",
            "    try {",
            "      if (typeof GPU !== 'undefined' && GPU.prototype) {",
            "        Object.setPrototypeOf(gpu, GPU.prototype);",
            "      }",
            "    } catch (_) {}",
            "    return gpu;",
            "  };",
            "  const keyboard = buildKeyboard();",
            "  const mediaCapabilities = buildMediaCapabilities();",
            "  const gpu = buildGpu();",
            "  try {",
            "    if (typeof NetworkInformation !== 'undefined' && NetworkInformation.prototype) {",
            "      Object.setPrototypeOf(connection, NetworkInformation.prototype);",
            "    }",
            "  } catch (_) {}",
            "  installDescriptor(Navigator.prototype, 'connection', () => connection);",
            "  installDescriptor(Navigator.prototype, 'mozConnection', () => connection);",
            "  installDescriptor(Navigator.prototype, 'webkitConnection', () => connection);",
            "  installDescriptor(Navigator.prototype, 'maxTouchPoints', () => maxTouchPoints);",
            "  installDescriptor(Navigator.prototype, 'keyboard', () => keyboard);",
            "  installDescriptor(Navigator.prototype, 'mediaCapabilities', () => mediaCapabilities);",
            "  installDescriptor(Navigator.prototype, 'gpu', () => gpu);",
            "  const buildOrientation = () => {",
            "    let nativeOrientation = null;",
            "    try { nativeOrientation = typeof screen !== 'undefined' ? screen.orientation : null; } catch (_) {}",
            "    if (nativeOrientation && typeof nativeOrientation === 'object') {",
            "      const wrapped = Object.create(Object.getPrototypeOf(nativeOrientation) || Object.prototype);",
            "      installDescriptor(wrapped, 'angle', () => orientationAngle);",
            "      installDescriptor(wrapped, 'type', () => orientationType);",
            "      installDescriptor(wrapped, 'onchange', () => nativeOrientation.onchange || null);",
            "      wrapped.addEventListener = (...args) => nativeOrientation.addEventListener ? nativeOrientation.addEventListener(...args) : undefined;",
            "      wrapped.removeEventListener = (...args) => nativeOrientation.removeEventListener ? nativeOrientation.removeEventListener(...args) : undefined;",
            "      wrapped.dispatchEvent = (...args) => nativeOrientation.dispatchEvent ? nativeOrientation.dispatchEvent(...args) : true;",
            "      wrapped.lock = (...args) => nativeOrientation.lock ? nativeOrientation.lock(...args) : Promise.resolve(orientationType);",
            "      wrapped.unlock = (...args) => nativeOrientation.unlock ? nativeOrientation.unlock(...args) : undefined;",
            "      return wrapped;",
            "    }",
            "    return {",
            "      angle: orientationAngle,",
            "      type: orientationType,",
            "      onchange: null,",
            "      addEventListener() {},",
            "      removeEventListener() {},",
            "      dispatchEvent() { return true; },",
            "      lock() { return Promise.resolve(orientationType); },",
            "      unlock() {},",
            "    };",
            "  };",
            "  const orientation = buildOrientation();",
            "  if (typeof Screen !== 'undefined' && Screen.prototype) {",
            "    installDescriptor(Screen.prototype, 'orientation', () => orientation);",
            "  } else if (typeof screen !== 'undefined') {",
            "    installDescriptor(screen, 'orientation', () => orientation);",
            "  }",
            "})();",
        ]
    )


def build_intl_coherence_init_script(
    *,
    locale: str,
    timezone_id: str | None,
) -> str:
    return "\n".join(
        [
            "(() => {",
            f"  const locale = {json.dumps(locale)};",
            f"  const timezoneId = {json.dumps(timezone_id)};",
            "  const shouldInjectLocale = (value) => {",
            "    if (value === undefined || value === null || value === '') {",
            "      return true;",
            "    }",
            "    return Array.isArray(value) && value.length === 0;",
            "  };",
            "  const nativeLocaleOrFallback = (value) => {",
            "    const normalized = String(value || '').trim();",
            "    return normalized || locale;",
            "  };",
            "  const patchIntlConstructor = (name, resolvedOptionsPatch) => {",
            "    const NativeCtor = Intl[name];",
            "    if (typeof NativeCtor !== 'function' || !NativeCtor.prototype || typeof NativeCtor.prototype.resolvedOptions !== 'function') {",
            "      return;",
            "    }",
            "    const nativeResolvedOptions = NativeCtor.prototype.resolvedOptions;",
            "    const PatchedCtor = function IntlConstructor(...args) {",
            "      const normalizedArgs = [...args];",
            "      if (shouldInjectLocale(normalizedArgs[0])) {",
            "        normalizedArgs[0] = locale;",
            "      }",
            "      const formatter = new NativeCtor(...normalizedArgs);",
            "      return new Proxy(formatter, {",
            "        get(target, prop, receiver) {",
            "          if (prop === 'resolvedOptions') {",
            "            return () => ({",
            "              ...nativeResolvedOptions.call(target),",
            "              ...resolvedOptionsPatch(target, nativeResolvedOptions),",
            "            });",
            "          }",
            "          return Reflect.get(target, prop, receiver);",
            "        },",
            "      });",
            "    };",
            "    for (const key of [...Object.getOwnPropertyNames(NativeCtor), ...Object.getOwnPropertySymbols(NativeCtor)]) {",
            "      if (key === 'prototype') {",
            "        continue;",
            "      }",
            "      try {",
            "        const descriptor = Object.getOwnPropertyDescriptor(NativeCtor, key);",
            "        if (!descriptor) {",
            "          continue;",
            "        }",
            "        if (typeof descriptor.value === 'function') {",
            "          descriptor.value = descriptor.value.bind(NativeCtor);",
            "        }",
            "        Object.defineProperty(PatchedCtor, key, descriptor);",
            "      } catch (_) {}",
            "    }",
            "    try {",
            "      Object.defineProperty(PatchedCtor, 'prototype', { value: NativeCtor.prototype });",
            "    } catch (_) {",
            "      PatchedCtor.prototype = NativeCtor.prototype;",
            "    }",
            "    try {",
            "      Object.defineProperty(PatchedCtor, 'toString', {",
            "        value: NativeCtor.toString.bind(NativeCtor),",
            "        configurable: true,",
            "      });",
            "    } catch (_) {}",
            "    Intl[name] = PatchedCtor;",
            "  };",
            "  patchIntlConstructor('DateTimeFormat', (target, resolvedOptions) => ({",
            "    locale: nativeLocaleOrFallback(resolvedOptions.call(target).locale),",
            "    ...(timezoneId ? { timeZone: timezoneId } : {}),",
            "  }));",
            "  patchIntlConstructor('NumberFormat', (target, resolvedOptions) => ({ locale: nativeLocaleOrFallback(resolvedOptions.call(target).locale) }));",
            "  patchIntlConstructor('Collator', (target, resolvedOptions) => ({ locale: nativeLocaleOrFallback(resolvedOptions.call(target).locale) }));",
            "  patchIntlConstructor('ListFormat', (target, resolvedOptions) => ({ locale: nativeLocaleOrFallback(resolvedOptions.call(target).locale) }));",
            "  patchIntlConstructor('PluralRules', (target, resolvedOptions) => ({ locale: nativeLocaleOrFallback(resolvedOptions.call(target).locale) }));",
            "})();",
        ]
    )


def build_performance_coherence_init_script() -> str:
    return "\n".join(
        [
            "(() => {",
            "  if (typeof Performance === 'undefined' || !Performance.prototype || typeof Performance.prototype.getEntriesByType !== 'function') {",
            "    return;",
            "  }",
            "  const nativeGetEntriesByType = Performance.prototype.getEntriesByType;",
            "  const monotonic = (previous, candidate, step) => {",
            "    const value = Number.isFinite(candidate) ? Number(candidate) : previous + step;",
            "    return Math.max(previous + step, value);",
            "  };",
            "  const normalizeNavigationEntry = (entry) => {",
            "    if (!entry || typeof entry !== 'object') {",
            "      return entry;",
            "    }",
            "    const fetchStart = Math.max(0.8, Number(entry.fetchStart) || 0.8);",
            "    const domainLookupStart = monotonic(fetchStart, entry.domainLookupStart, 0.4);",
            "    const domainLookupEnd = monotonic(domainLookupStart, entry.domainLookupEnd, 2.5);",
            "    const connectStart = monotonic(domainLookupEnd, entry.connectStart, 0.5);",
            "    const secureConnectionStart = monotonic(connectStart, entry.secureConnectionStart, 0.5);",
            "    const connectEnd = monotonic(secureConnectionStart, entry.connectEnd, 4.5);",
            "    const requestStart = monotonic(connectEnd, entry.requestStart, 1.8);",
            "    const responseStart = monotonic(requestStart, entry.responseStart, 65);",
            "    const responseEnd = monotonic(responseStart, entry.responseEnd, 38);",
            "    const domInteractive = monotonic(responseEnd, entry.domInteractive, 80);",
            "    const domContentLoadedEventStart = monotonic(domInteractive, entry.domContentLoadedEventStart, 18);",
            "    const domContentLoadedEventEnd = monotonic(domContentLoadedEventStart, entry.domContentLoadedEventEnd, 12);",
            "    const loadEventStart = monotonic(domContentLoadedEventEnd, entry.loadEventStart, 70);",
            "    const loadEventEnd = monotonic(loadEventStart, entry.loadEventEnd, 12);",
            "    const overrides = {",
            "      startTime: 0,",
            "      fetchStart,",
            "      domainLookupStart,",
            "      domainLookupEnd,",
            "      connectStart,",
            "      secureConnectionStart,",
            "      connectEnd,",
            "      requestStart,",
            "      responseStart,",
            "      responseEnd,",
            "      domInteractive,",
            "      domContentLoadedEventStart,",
            "      domContentLoadedEventEnd,",
            "      loadEventStart,",
            "      loadEventEnd,",
            "      duration: loadEventEnd,",
            "    };",
            "    return new Proxy(entry, {",
            "      get(target, prop, receiver) {",
            "        if (prop in overrides) {",
            "          return overrides[prop];",
            "        }",
            "        if (prop === 'toJSON') {",
            "          return () => ({ ...(typeof target.toJSON === 'function' ? target.toJSON() : {}), ...overrides });",
            "        }",
            "        return Reflect.get(target, prop, receiver);",
            "      },",
            "    });",
            "  };",
            "  Performance.prototype.getEntriesByType = function getEntriesByType(type) {",
            "    const entries = nativeGetEntriesByType.call(this, type);",
            "    if (String(type || '').toLowerCase() !== 'navigation' || !Array.isArray(entries)) {",
            "      return entries;",
            "    }",
            "    return entries.map(normalizeNavigationEntry);",
            "  };",
            "})();",
        ]
    )
