from __future__ import annotations

HOST_OS_UA_TOKENS: dict[str, str] = {
    "windows": "windows nt",
    "macos": "macintosh",
    "linux": "linux",
}

HOST_OS_PLATFORM_LABELS: dict[str, str] = {
    "windows": "Windows",
    "macos": "macOS",
    "linux": "Linux",
}

USER_AGENT_PLATFORM_LABELS: tuple[tuple[str, str], ...] = (
    ("windows nt", "Windows"),
    ("macintosh", "macOS"),
    ("mac os x", "macOS"),
    ("linux", "Linux"),
)

NAVIGATOR_PLATFORM_BY_PLATFORM_LABEL: dict[str, str] = {
    "Windows": "Win32",
    "macOS": "MacIntel",
    "Linux": "Linux x86_64",
}

TIMEZONE_ALIASES: dict[str, str] = {
    "asia/calcutta": "Asia/Kolkata",
}

DEVICE_MEMORY_BUCKETS: tuple[float, ...] = (0.25, 0.5, 1.0, 2.0, 4.0, 8.0)

NATIVE_REAL_CHROME_CONTEXT_OPTIONS: dict[str, object] = {"no_viewport": True}
WARMUP_ELIGIBLE_BROWSER_REASONS: frozenset[str] = frozenset(
    {
        "host-preference",
        "http-escalation",
        "platform-required",
        "traversal-required",
        "empty-extraction retry",
        "thin-listing retry",
    }
)
WARMUP_VENDOR_BLOCK_PREFIX = "vendor-block:"

WEBGL_PROFILE_BY_PLATFORM: dict[str, dict[str, object]] = {
    "Windows": {
        "vendor": "Google Inc.",
        "renderer": "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)",
        "version": "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
        "shading_language_version": "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
        "max_texture_size": 16384,
        "max_renderbuffer_size": 16384,
        "max_cube_map_texture_size": 16384,
        "max_viewport_dims": [16384, 16384],
        "max_texture_image_units": 16,
        "max_combined_texture_image_units": 32,
        "max_vertex_texture_image_units": 16,
        "max_vertex_attribs": 16,
        "max_vertex_uniform_vectors": 1024,
        "max_fragment_uniform_vectors": 1024,
        "aliased_line_width_range": [1, 1],
        "aliased_point_size_range": [1, 1024],
        "max_anisotropy": 16,
        "supported_extensions": [
            "ANGLE_instanced_arrays",
            "EXT_blend_minmax",
            "EXT_color_buffer_half_float",
            "EXT_disjoint_timer_query",
            "EXT_frag_depth",
            "EXT_shader_texture_lod",
            "EXT_texture_filter_anisotropic",
            "OES_element_index_uint",
            "OES_standard_derivatives",
            "OES_texture_float",
            "OES_texture_float_linear",
            "OES_texture_half_float",
            "OES_texture_half_float_linear",
            "OES_vertex_array_object",
            "WEBGL_color_buffer_float",
            "WEBGL_compressed_texture_s3tc",
            "WEBGL_debug_renderer_info",
            "WEBGL_debug_shaders",
            "WEBGL_depth_texture",
            "WEBGL_draw_buffers",
            "WEBGL_lose_context",
        ],
    },
    "macOS": {
        "vendor": "Intel Inc.",
        "renderer": "Intel(R) Iris OpenGL Engine",
        "version": "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
        "shading_language_version": "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
        "max_texture_size": 16384,
        "max_renderbuffer_size": 16384,
        "max_cube_map_texture_size": 16384,
        "max_viewport_dims": [16384, 16384],
        "max_texture_image_units": 16,
        "max_combined_texture_image_units": 32,
        "max_vertex_texture_image_units": 16,
        "max_vertex_attribs": 16,
        "max_vertex_uniform_vectors": 1024,
        "max_fragment_uniform_vectors": 1024,
        "aliased_line_width_range": [1, 1],
        "aliased_point_size_range": [1, 511],
        "max_anisotropy": 16,
        "supported_extensions": [
            "EXT_blend_minmax",
            "EXT_color_buffer_half_float",
            "EXT_frag_depth",
            "EXT_shader_texture_lod",
            "EXT_texture_filter_anisotropic",
            "OES_element_index_uint",
            "OES_standard_derivatives",
            "OES_texture_float",
            "OES_texture_float_linear",
            "OES_texture_half_float",
            "OES_texture_half_float_linear",
            "OES_vertex_array_object",
            "WEBGL_color_buffer_float",
            "WEBGL_compressed_texture_s3tc",
            "WEBGL_debug_renderer_info",
            "WEBGL_debug_shaders",
            "WEBGL_depth_texture",
            "WEBGL_draw_buffers",
            "WEBGL_lose_context",
        ],
    },
    "Linux": {
        "vendor": "Google Inc.",
        "renderer": "ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6)",
        "version": "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
        "shading_language_version": "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
        "max_texture_size": 16384,
        "max_renderbuffer_size": 16384,
        "max_cube_map_texture_size": 16384,
        "max_viewport_dims": [16384, 16384],
        "max_texture_image_units": 16,
        "max_combined_texture_image_units": 32,
        "max_vertex_texture_image_units": 16,
        "max_vertex_attribs": 16,
        "max_vertex_uniform_vectors": 1024,
        "max_fragment_uniform_vectors": 1024,
        "aliased_line_width_range": [1, 1],
        "aliased_point_size_range": [1, 1024],
        "max_anisotropy": 16,
        "supported_extensions": [
            "ANGLE_instanced_arrays",
            "EXT_blend_minmax",
            "EXT_color_buffer_half_float",
            "EXT_frag_depth",
            "EXT_shader_texture_lod",
            "EXT_texture_filter_anisotropic",
            "OES_element_index_uint",
            "OES_standard_derivatives",
            "OES_texture_float",
            "OES_texture_float_linear",
            "OES_texture_half_float",
            "OES_texture_half_float_linear",
            "OES_vertex_array_object",
            "WEBGL_color_buffer_float",
            "WEBGL_compressed_texture_s3tc",
            "WEBGL_debug_renderer_info",
            "WEBGL_debug_shaders",
            "WEBGL_depth_texture",
            "WEBGL_draw_buffers",
            "WEBGL_lose_context",
        ],
    },
    "mobile": {
        "vendor": "Qualcomm",
        "renderer": "Adreno (TM) 640",
        "version": "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
        "shading_language_version": "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
        "max_texture_size": 8192,
        "max_renderbuffer_size": 8192,
        "max_cube_map_texture_size": 8192,
        "max_viewport_dims": [8192, 8192],
        "max_texture_image_units": 16,
        "max_combined_texture_image_units": 24,
        "max_vertex_texture_image_units": 16,
        "max_vertex_attribs": 16,
        "max_vertex_uniform_vectors": 256,
        "max_fragment_uniform_vectors": 224,
        "aliased_line_width_range": [1, 1],
        "aliased_point_size_range": [1, 511],
        "max_anisotropy": 8,
        "supported_extensions": [
            "EXT_blend_minmax",
            "EXT_color_buffer_half_float",
            "EXT_frag_depth",
            "EXT_shader_texture_lod",
            "EXT_texture_filter_anisotropic",
            "OES_element_index_uint",
            "OES_standard_derivatives",
            "OES_texture_float",
            "OES_texture_half_float",
            "OES_vertex_array_object",
            "WEBGL_color_buffer_float",
            "WEBGL_debug_renderer_info",
            "WEBGL_depth_texture",
            "WEBGL_draw_buffers",
            "WEBGL_lose_context",
        ],
    },
}

FONT_ALLOWLIST_BY_PLATFORM: dict[str, tuple[str, ...]] = {
    "Windows": (
        "arial",
        "arial black",
        "bahnschrift",
        "calibri",
        "cambria",
        "candara",
        "comic sans ms",
        "consolas",
        "constantia",
        "corbel",
        "courier new",
        "franklin gothic medium",
        "gabriola",
        "georgia",
        "impact",
        "lucida console",
        "lucida sans unicode",
        "palatino linotype",
        "segoe print",
        "segoe script",
        "segoe ui",
        "segoe ui emoji",
        "tahoma",
        "times new roman",
        "trebuchet ms",
        "verdana",
    ),
    "macOS": (
        "american typewriter",
        "arial",
        "avenir",
        "avenir next",
        "baskerville",
        "courier",
        "courier new",
        "futura",
        "geneva",
        "georgia",
        "helvetica",
        "helvetica neue",
        "menlo",
        "monaco",
        "optima",
        "palatino",
        "san francisco",
        "sf pro display",
        "sf pro text",
        "times",
        "times new roman",
        "verdana",
    ),
    "Linux": (
        "arial",
        "cantarell",
        "dejavu sans",
        "dejavu sans mono",
        "dejavu serif",
        "droid sans",
        "free mono",
        "free sans",
        "free serif",
        "liberation mono",
        "liberation sans",
        "liberation serif",
        "noto color emoji",
        "noto sans",
        "noto sans mono",
        "noto serif",
        "ubuntu",
        "ubuntu mono",
        "verdana",
    ),
    "mobile": (
        "arial",
        "arial hebrew",
        "courier new",
        "droid sans",
        "georgia",
        "helvetica",
        "helvetica neue",
        "noto sans",
        "noto sans jp",
        "noto sans kr",
        "noto sans sc",
        "noto sans tc",
        "noto serif",
        "roboto",
        "roboto condensed",
        "roboto mono",
        "san francisco",
        "sf pro display",
        "sf pro text",
        "times new roman",
        "verdana",
    ),
}


__all__ = [
    "DEVICE_MEMORY_BUCKETS",
    "FONT_ALLOWLIST_BY_PLATFORM",
    "HOST_OS_PLATFORM_LABELS",
    "HOST_OS_UA_TOKENS",
    "NAVIGATOR_PLATFORM_BY_PLATFORM_LABEL",
    "TIMEZONE_ALIASES",
    "USER_AGENT_PLATFORM_LABELS",
    "WEBGL_PROFILE_BY_PLATFORM",
]
