from __future__ import annotations

from app.services.config._module_exports import make_getattr, module_dir
from app.services.config.runtime_settings import crawler_runtime_settings

_SETTINGS_EXPORTS = {
    name: name.lower()
    for name in (
        "HTTP_TIMEOUT_SECONDS",
        "ACQUISITION_ATTEMPT_TIMEOUT_SECONDS",
        "IMPERSONATION_TARGET",
        "HTTP_IMPERSONATION_PROFILES",
        "HTTP_STEALTH_IMPERSONATION_PROFILE",
        "BROWSER_FALLBACK_VISIBLE_TEXT_MIN",
        "BROWSER_FALLBACK_VISIBLE_TEXT_RATIO_MAX",
        "BROWSER_FALLBACK_HTML_SIZE_THRESHOLD",
        "JS_GATE_PHRASES",
        "DEFAULT_MAX_RECORDS",
        "DEFAULT_MAX_PAGES",
        "MIN_MAX_PAGES",
        "MAX_MAX_PAGES",
        "DEFAULT_SLEEP_MS",
        "MIN_REQUEST_DELAY_MS",
        "DEFAULT_MAX_SCROLLS",
        "AUTO_DETECT_SURFACE",
        "BATCH_URL_CONCURRENCY",
        "URL_BATCH_CONCURRENCY",
        "URL_PROCESS_TIMEOUT_SECONDS",
        "MAX_URL_PROCESS_TIMEOUT_SECONDS",
        "WORKER_MAX_CONCURRENT_JOBS",
        "WORKER_ORPHAN_RECOVERY_GRACE_SECONDS",
        "MAX_CANDIDATES_PER_FIELD",
        "DYNAMIC_FIELD_NAME_MAX_TOKENS",
        "ACCORDION_EXPAND_MAX",
        "ACCORDION_EXPAND_WAIT_MS",
        "BLOCK_MIN_HTML_LENGTH",
        "BLOCK_LOW_CONTENT_TEXT_MAX",
        "BLOCK_LOW_CONTENT_SCRIPT_MIN",
        "BLOCK_LOW_CONTENT_LINK_MAX",
        "LISTING_MIN_ITEMS",
        "CARD_AUTODETECT_MIN_SIBLINGS",
        "JSON_MAX_SEARCH_DEPTH",
        "MAX_JSON_RECURSION_DEPTH",
        "JS_SHELL_MIN_CONTENT_LEN",
        "JS_SHELL_VISIBLE_RATIO_MAX",
        "JS_SHELL_MIN_SCRIPT_COUNT",
        "DETAIL_FIELD_SIGNAL_MIN_COUNT",
        "HTTP_RETRY_STATUS_CODES",
        "HTTP_MAX_RETRIES",
        "HTTP_RETRY_BACKOFF_BASE_MS",
        "HTTP_RETRY_BACKOFF_MAX_MS",
        "PROXY_FAILURE_COOLDOWN_BASE_MS",
        "PROXY_FAILURE_COOLDOWN_MAX_MS",
        "PROXY_FAILURE_BACKOFF_MAX_EXPONENT",
        "PROXY_FAILURE_STATE_TTL_SECONDS",
        "PROXY_FAILURE_STATE_MAX_ENTRIES",
        "DNS_RESOLUTION_RETRIES",
        "DNS_RESOLUTION_RETRY_DELAY_MS",
        "ACQUIRE_HOST_MIN_INTERVAL_MS",
        "PACING_HOST_CACHE_MAX_ENTRIES",
        "PACING_HOST_CACHE_TTL_SECONDS",
        "STEALTH_PREFER_TTL_HOURS",
        "CHALLENGE_WAIT_MAX_SECONDS",
        "CHALLENGE_POLL_INTERVAL_MS",
        "SURFACE_READINESS_MAX_WAIT_MS",
        "SURFACE_READINESS_POLL_MS",
        "ORIGIN_WARM_PAUSE_MS",
        "BROWSER_ERROR_RETRY_ATTEMPTS",
        "BROWSER_ERROR_RETRY_DELAY_MS",
        "BROWSER_NAVIGATION_NETWORKIDLE_TIMEOUT_MS",
        "BROWSER_NAVIGATION_LOAD_TIMEOUT_MS",
        "BROWSER_NAVIGATION_DOMCONTENTLOADED_TIMEOUT_MS",
        "BROWSER_NAVIGATION_OPTIMISTIC_WAIT_MS",
        "BROWSER_NAVIGATION_MIN_COMMIT_WAIT_MS",
        "BROWSER_NAVIGATION_MIN_FINAL_COMMIT_TIMEOUT_MS",
        "INTERRUPTIBLE_WAIT_POLL_MS",
        "COOPERATIVE_SLEEP_POLL_MS",
        "PAGINATION_NAVIGATION_TIMEOUT_MS",
        "PAGINATION_PAGE_SIZE_ANOMALY_RATIO",
        "PAGINATION_POST_CLICK_TIMEOUT_MS",
        "PAGINATION_POST_CLICK_DOMCONTENTLOADED_TIMEOUT_MS",
        "PAGINATION_POST_CLICK_POLL_MS",
        "PAGINATION_POST_CLICK_SETTLE_TIMEOUT_MS",
        "LISTING_READINESS_MAX_WAIT_MS",
        "LISTING_READINESS_POLL_MS",
        "SCROLL_WAIT_MIN_MS",
        "LOAD_MORE_WAIT_MIN_MS",
        "TRAVERSAL_MAX_ITERATIONS_CAP",
        "TRAVERSAL_MIN_SETTLE_WAIT_MS",
        "TRAVERSAL_WEAK_PROGRESS_STREAK_MAX",
        "TRAVERSAL_ACTIVE_SCROLLABLE_THRESHOLD_PX",
        "TRAVERSAL_ACTIVE_SCROLLABLE_BONUS",
        "TRAVERSAL_ACTIVE_LINK_WEIGHT",
        "TRAVERSAL_ACTIVE_TARGET_LABEL_MAX_LEN",
        "TRAVERSAL_FORCE_PROBE_MIN_ADVANCE_PX",
        "INFINITE_SCROLL_CONTAINER_OVERFLOW_THRESHOLD_PX",
        "INFINITE_SCROLL_TALL_PAGE_RATIO",
        "INFINITE_SCROLL_POSITIVE_SIGNAL_MIN",
        "COOKIE_CONSENT_PREWAIT_MS",
        "COOKIE_CONSENT_POSTCLICK_WAIT_MS",
        "SHADOW_DOM_FLATTEN_MAX_HOSTS",
        "BROWSER_CONTEXT_TIMEOUT_MS",
        "BROWSER_NEW_PAGE_TIMEOUT_MS",
        "BROWSER_CLOSE_TIMEOUT_MS",
        "BROWSER_RENDER_TIMEOUT_SECONDS",
        "IFRAME_PROMOTION_MAX_CANDIDATES",
        "EXTRACTABILITY_NON_PRODUCT_TYPE_RATIO_MAX",
        "EXTRACTABILITY_JSON_LD_MIN_TYPE_SIGNALS",
        "EXTRACTABILITY_NEXT_DATA_SIGNAL_TRIGGER",
        "EXTRACTABILITY_NEXT_DATA_SIGNAL_MIN",
        "BROWSER_PREFERENCE_MIN_SUCCESSES",
        "ACQUISITION_ARTIFACT_TTL_SECONDS",
        "ACQUISITION_ARTIFACT_CLEANUP_INTERVAL_SECONDS",
    )
}
_STATIC_EXPORTS = {
    "LONG_RUN_THRESHOLD_SECONDS": 30 * 60,
    "MAX_DURATION_SAMPLE_SIZE": 1000,
    "STALLED_RUN_THRESHOLD_SECONDS": 2 * 60,
    "STEALTH_MIN_TTL_HOURS": 1,
}

__all__ = sorted(
    [*_SETTINGS_EXPORTS.keys(), *_STATIC_EXPORTS.keys(), "coerce_url_timeout_seconds"]
)

__getattr__ = make_getattr(
    attr_exports=_SETTINGS_EXPORTS,
    value_exports=_STATIC_EXPORTS,
    settings_obj=crawler_runtime_settings,
)


def __dir__() -> list[str]:
    return module_dir(globals(), __all__)


def coerce_url_timeout_seconds(value: object) -> float:
    return crawler_runtime_settings.coerce_url_timeout_seconds(value)
