from __future__ import annotations

DOMAIN_PROFILE_SCHEMA_VERSION = 2
SELECTOR_RULE_STALE_AFTER_DAYS = 14
ACQUISITION_CONTRACT_MAX_FAILURES = 3
FALLBACK_SURFACE = "ecommerce_detail"
AUTO_SURFACE = "auto"
DEFAULT_FALLBACK_SURFACE = "generic"
INVALID_SURFACE_VALUES = frozenset({AUTO_SURFACE})
SURFACE_VALIDATION_ERROR = "surface must be explicit"
TRAVERSAL_MODE_VALUES = frozenset({"scroll", "load_more", "view_all", "paginate"})
LISTING_SURFACE_IDENTIFIER = "listing"
SURFACE_PAIRS = {
    "ecommerce_listing": "ecommerce_detail",
    "ecommerce_detail": "ecommerce_listing",
    "job_listing": "job_detail",
    "job_detail": "job_listing",
}
ALTERNATE_MIN_RECORDS = 2
ALTERNATE_MAX_RECORDS = 3
ALTERNATE_MISMATCH_WARNING_THRESHOLD = 2

__all__ = [
    "ACQUISITION_CONTRACT_MAX_FAILURES",
    "ALTERNATE_MAX_RECORDS",
    "ALTERNATE_MIN_RECORDS",
    "ALTERNATE_MISMATCH_WARNING_THRESHOLD",
    "AUTO_SURFACE",
    "DEFAULT_FALLBACK_SURFACE",
    "DOMAIN_PROFILE_SCHEMA_VERSION",
    "FALLBACK_SURFACE",
    "INVALID_SURFACE_VALUES",
    "LISTING_SURFACE_IDENTIFIER",
    "SELECTOR_RULE_STALE_AFTER_DAYS",
    "SURFACE_PAIRS",
    "SURFACE_VALIDATION_ERROR",
    "TRAVERSAL_MODE_VALUES",
]
