from __future__ import annotations

DOMAIN_PROFILE_SCHEMA_VERSION = 2
SELECTOR_RULE_STALE_AFTER_DAYS = 14
ACQUISITION_CONTRACT_MAX_FAILURES = 3
FALLBACK_SURFACE = "ecommerce_detail"

__all__ = [
    "ACQUISITION_CONTRACT_MAX_FAILURES",
    "DOMAIN_PROFILE_SCHEMA_VERSION",
    "FALLBACK_SURFACE",
    "SELECTOR_RULE_STALE_AFTER_DAYS",
]

