from __future__ import annotations

PIPELINE_TUNING = {
    "http_timeout_seconds": 20,
    "impersonation_target": "chrome131",
    "http_impersonation_profiles": ["chrome110", "chrome116", "chrome123", "chrome131"],
    "http_stealth_impersonation_profile": "chrome131",
    "browser_fallback_visible_text_min": 500,
    "browser_fallback_visible_text_ratio_max": 0.02,
    "browser_fallback_html_size_threshold": 200000,
    "js_gate_phrases": ["enable javascript", "<noscript>"],
    "default_max_records": 100,
    "default_sleep_ms": 0,
    "min_request_delay_ms": 100,
    "block_min_html_length": 100,
    "block_low_content_text_max": 500,
    "block_low_content_script_min": 3,
    "block_low_content_link_max": 3,
    "listing_min_items": 2,
    "card_autodetect_min_siblings": 3,
    "json_max_search_depth": 5,
    "max_json_recursion_depth": 4,
    "http_retry_status_codes": [403, 429, 503],
    "http_max_retries": 2,
    "http_retry_backoff_base_ms": 400,
    "http_retry_backoff_max_ms": 3000,
    "dns_resolution_retries": 1,
    "dns_resolution_retry_delay_ms": 250,
    "acquire_host_min_interval_ms": 250,
    "pacing_host_cache_max_entries": 1024,
    "pacing_host_cache_ttl_seconds": 3600,
    "stealth_prefer_ttl_hours": 24,
    "_timing_validation_note": "http_timeout_seconds, challenge_wait_max_seconds, surface_readiness_max_wait_ms, origin_warm_pause_ms, scroll_wait_min_ms, and load_more_wait_min_ms must be validated against production traffic before lowering further.",
    "challenge_wait_max_seconds": 12,
    "challenge_poll_interval_ms": 1000,
    "surface_readiness_max_wait_ms": 12000,
    "surface_readiness_poll_ms": 250,
    "origin_warm_pause_ms": 2000,
    "browser_error_retry_attempts": 1,
    "browser_error_retry_delay_ms": 1000,
    "browser_navigation_networkidle_timeout_ms": 30000,
    "browser_navigation_load_timeout_ms": 15000,
    "browser_navigation_domcontentloaded_timeout_ms": 15000,
    "pagination_navigation_timeout_ms": 20000,
    "listing_readiness_max_wait_ms": 6000,
    "listing_readiness_poll_ms": 500,
    "scroll_wait_min_ms": 1500,
    "load_more_wait_min_ms": 2000,
    "cookie_consent_prewait_ms": 400,
    "cookie_consent_postclick_wait_ms": 600,
    "shadow_dom_flatten_max_hosts": 100,
    "default_max_scrolls": 10,
    "max_candidates_per_field": 5,
    "dynamic_field_name_max_tokens": 7,
    "accordion_expand_max": 20,
    "accordion_expand_wait_ms": 500,
}

SITE_POLICY_REGISTRY = {}

EXTRACTION_RULES = {
    "field_aliases": {
        "title": [
            "title",
            "name",
            "job_title",
            "position",
            "headline",
            "productName",
            "product_name",
        ],
        "url": [
            "url",
            "link",
            "href",
            "apply_url",
            "canonical_url",
            "product_url",
            "landingPageUrl",
            "detailPageLink",
            "detail_page_link",
            "position_uri",
        ],
        "slug": ["slug"],
        "price": ["price", "amount", "cost", "sale_price", "current_price"],
        "sale_price": [
            "sale_price",
            "saleprice",
            "sellingprice",
            "newprice",
            "discount_price",
            "discountedPrice",
        ],
        "original_price": [
            "compare_at_price",
            "list_price",
            "regular_price",
            "was_price",
            "original_price",
            "mrp",
        ],
        "currency": ["currency", "currency_code", "price_currency"],
        "brand": [
            "brand",
            "vendor",
            "manufacturer",
            "company_name",
            "brand_name",
            "designer",
        ],
        "image_url": [
            "image",
            "image_url",
            "thumbnail",
            "img",
            "photo",
            "logo",
            "featured_image",
            "primary_image",
            "searchImage",
        ],
        "additional_images": [
            "image",
            "images",
            "gallery",
            "gallery_images",
            "product_images",
            "media",
            "photos",
            "assets",
        ],
        "color": ["color", "colors", "color_name", "frame_color"],
        "finish": ["finish", "surface_finish", "texture"],
        "size": ["size", "sizes", "variant_size", "dimension_label"],
        "description": [
            "description",
            "body",
            "summary",
            "snippet",
            "content",
            "body_html",
            "short_description",
        ],
        "company": [
            "company",
            "company_name",
            "companyName",
            "organization",
            "employer",
            "hiring_organization",
            "agency",
        ],
        "location": [
            "location",
            "candidate_required_location",
            "job_location",
            "city",
            "region",
        ],
        "salary": [
            "salary",
            "compensation",
            "pay",
            "salary_range",
            "base_salary",
            "pay_range",
            "compensation_range",
            "salary_display",
        ],
        "category": [
            "category",
            "department",
            "product_type",
            "job_type",
            "employment_type",
        ],
        "sku": ["sku", "product_id", "item_id", "id"],
        "part_number": [
            "part_number",
            "part",
            "part_no",
            "partNumber",
            "mpn",
            "manufacturer_part_number",
        ],
        "availability": ["availability", "in_stock", "stock_status"],
        "tags": ["tags", "labels", "keywords"],
        "rating": [
            "rating",
            "average_rating",
            "score",
            "rating_value",
            "aggregate_rating",
        ],
        "review_count": ["review_count", "total_reviews", "num_reviews"],
        "publication_date": [
            "publication_date",
            "date",
            "created_at",
            "posted_at",
            "published_at",
            "pub_date",
            "date_posted",
        ],
        "posted_date": ["posted_date", "date_posted", "publication_date", "posted_at"],
        "apply_url": ["apply_url", "application_url", "job_url", "product_link"],
        "responsibilities": [
            "responsibilities",
            "duties",
            "job_duties",
            "what_you_ll_do",
            "what_you_will_do",
        ],
        "qualifications": [
            "qualifications",
            "job_qualification",
            "prerequisites",
            "minimum_requirements",
            "preferred_qualifications",
            "who_you_are",
        ],
        "benefits": [
            "benefits",
            "job_benefits",
            "perks",
            "compensation_benefits",
            "what_we_offer",
        ],
        "skills": [
            "skills",
            "job_skills",
            "competencies",
            "abilities",
            "experience",
            "what_you_ll_bring",
        ],
        "remote": ["remote", "work_from_home", "wfh", "telecommute"],
        "specifications": [
            "specifications",
            "details",
            "technical_details",
            "product_details",
            "the_details",
        ],
        "features": ["features", "highlights", "key_features"],
        "materials": ["materials", "fabric", "composition", "fabric_content"],
        "care": ["care", "care_instructions", "product_care"],
        "dimensions": ["dimensions", "sizing", "measurements"],
        "summary": ["summary", "overview", "about"],
        "requirements": ["requirements", "job_requirements", "prerequisites"],
        "job_type": ["job_type", "employment_type"],
        "make": ["make", "manufacturer"],
        "model": ["model"],
        "year": ["year"],
        "trim": ["trim"],
        "mileage": ["mileage", "distance"],
        "vin": ["vin"],
        "condition": ["condition"],
        "body_style": ["body_style", "body type"],
        "fuel_type": ["fuel_type", "fuel"],
        "transmission": ["transmission"],
        "drivetrain": ["drivetrain"],
        "exterior_color": ["exterior_color", "color"],
        "interior_color": ["interior_color"],
        "dealer_name": ["dealer_name", "dealer"],
    },
    "requested_field_aliases": {
        "salary": [
            "salary",
            "compensation",
            "pay",
            "salary range",
            "salary_range",
            "base salary",
            "base_salary",
            "pay range",
            "pay_range",
            "compensation range",
            "compensation_range",
            "salary display",
            "salary_display",
        ],
        "responsibilities": [
            "responsibilities",
            "job responsibilities",
            "key responsibilities",
            "duties",
            "job duties",
            "what you'll do",
            "what_you_ll_do",
            "what_you_will_do",
            "role responsibilities",
        ],
        "qualifications": [
            "qualifications",
            "job qualifications",
            "job_qualification",
            "prerequisites",
            "minimum requirements",
            "minimum_requirements",
            "preferred qualifications",
            "preferred_qualifications",
            "who you are",
            "what we're looking for",
        ],
        "benefits": [
            "benefits",
            "job benefits",
            "job_benefits",
            "perks",
            "why you'll love this job",
            "what we offer",
        ],
        "skills": [
            "skills",
            "job skills",
            "job_skills",
            "competencies",
            "abilities",
            "experience",
            "what you'll bring",
        ],
        "summary": [
            "summary",
            "overview",
            "about",
            "description",
            "our opportunity",
            "about the role",
            "about the team",
        ],
        "specifications": [
            "specifications",
            "specs",
            "spec",
            "details",
            "technical details",
            "tech specs",
            "product details",
            "the details",
        ],
        "features": ["features", "highlights", "key features"],
        "materials": ["materials", "fabric", "composition", "fabric content"],
        "care": ["care", "care instructions", "product care"],
        "dimensions": ["dimensions", "sizing", "measurements"],
        "remote": ["remote", "work from home", "wfh"],
        "requirements": ["requirements", "job_requirements", "prerequisites"],
    },
    "dom_patterns": {
        "title": "h1, [itemprop='name'], meta[property='og:title'], title",
        "price": "[itemprop='price'], .price, .product-price",
        "sale_price": ".sale-price, .discount-price, [data-sale-price]",
        "original_price": ".original-price, .compare-price, [data-original-price]",
        "description": "[itemprop='description'], .product-description, [data-description], meta[name='description'], meta[property='og:description']",
        "brand": "[itemprop='brand'], .brand, .product-brand",
        "image_url": "[itemprop='image'], meta[property='og:image']",
        "rating": "[itemprop='ratingValue']",
        "review_count": "[itemprop='reviewCount']",
        "sku": "[itemprop='sku']",
        "availability": "[itemprop='availability'], .availability, [data-stock], [data-availability]",
        "category": "[itemprop='category'], nav.breadcrumb li:last-child",
        "company": ".company-name, [itemprop='hiringOrganization'] [itemprop='name']",
        "location": ".job-location, [itemprop='jobLocation'] [itemprop='name']",
        "salary": ".salary, [itemprop='baseSalary']",
        "job_type": "[itemprop='employmentType']",
        "apply_url": "a[data-apply-url], a.apply-button",
        "responsibilities": "[data-section='responsibilities'], .responsibilities, #responsibilities",
        "qualifications": "[data-section='qualifications'], .qualifications, #qualifications",
        "benefits": "[data-section='benefits'], .benefits, #benefits",
        "skills": "[data-section='skills'], .skills, #skills",
        "specifications": "[data-section='specifications'], .specifications, .product-specifications, #specifications",
        "features": "[data-section='features'], .features, .product-features, #features",
    },
    "candidate_cleanup": {
        "placeholder_values": [
            "-",
            "—",
            "--",
            "n/a",
            "na",
            "none",
            "null",
            "undefined",
        ],
        "generic_category_values": [
            "detail-page",
            "detail_page",
            "product",
            "page",
            "pdp",
            "simple",
            "configurable",
            "image",
            "imageobject",
            "listitem",
            "itemlist",
            "collectionpage",
            "productcard",
            "contentcard",
            "aggregateoffer",
            "productgroup",
            "aggregaterating",
            "review",
            "person",
            "rating",
            "merchantreturnpolicy",
            "merchantreturnpolicyseasonaloverride",
            "webpage",
            "organization",
            "speakablespecification",
            "individualproduct",
            "peopleaudience",
            "brand",
            "offer",
            "postaladdress",
            "country",
            "quantitativevalue",
            "unitpricespecification",
            "pricespecification",
            "deliverychargespecification",
            "openinghoursspecification",
            "geopoint",
            "geocoordinates",
            "place",
            "contactpoint",
            "searchaction",
            "readaction",
            "buyaction",
            "sitenavigationelement",
            "wpadblock",
            "creativework",
            "article",
            "newsarticle",
            "blogposting",
            "howto",
            "faqpage",
            "videoobject",
            "localbusiness",
            "store",
            "thing",
        ],
        "generic_title_values": [
            "chrome",
            "firefox",
            "safari",
            "edge",
            "home",
            "cookie preferences",
            "cookie settings",
            "privacy preferences",
            "privacy settings",
            "manage cookies",
            "consent preferences",
            "accept cookies",
            "sign in",
            "log in",
            "my account",
            "newsletter",
            "create account",
            "register",
        ],
        "title_noise_tokens": [
            "cookie",
            "cookies",
            "privacy",
            "consent",
            "preferences",
            "sign in",
            "log in",
            "login",
            "register",
            "my account",
            "newsletter",
            "subscribe",
            "terms",
            "conditions",
            "gdpr",
            "ccpa",
        ],
        "ga_data_layer_keys": [
            "event",
            "ecommerce",
            "gtm.start",
            "gtm.uniqueEventId",
            "pageType",
            "pageName",
            "visitorType",
        ],
        "field_groups": {
            "url": ["url", "apply_url"],
            "image_primary": ["image_url"],
            "image_collection": ["additional_images"],
            "numeric": [
                "price",
                "sale_price",
                "original_price",
                "rating",
                "review_count",
            ],
            "salary": ["salary"],
            "currency": ["currency"],
            "availability": ["availability"],
            "category": ["category"],
            "title": ["title"],
            "description": ["description", "summary"],
            "job_text": [
                "responsibilities",
                "requirements",
                "qualifications",
                "benefits",
                "skills",
            ],
            "entity_name": ["brand", "company"],
            "identifier": ["sku", "vin", "dealer_name"],
        },
        "field_name_patterns": {
            "url_suffixes": ["_url", "url", "_link", "link", "_href", "href"],
            "image_tokens": [
                "image",
                "images",
                "gallery",
                "photo",
                "thumbnail",
                "hero",
            ],
            "currency_tokens": ["currency"],
            "price_tokens": ["price", "amount", "cost"],
            "salary_tokens": ["salary", "pay", "rate", "compensation"],
            "rating_tokens": ["rating", "score"],
            "review_count_tokens": ["review_count", "reviews", "rating_count"],
            "availability_tokens": ["availability", "stock"],
            "category_tokens": ["category", "department", "breadcrumb"],
            "description_tokens": ["description", "summary", "overview", "details"],
            "identifier_tokens": ["sku", "id", "code", "vin", "mpn"],
        },
        "ui_noise_phrases": [
            "add to wishlist",
            "add to bag",
            "add to cart",
            "buy now",
            "selling fast",
            "best seller",
            "top seller",
            "limited stock",
            "low stock",
            "sold out",
            "out of stock",
            "view more",
            "learn more",
        ],
        "ui_noise_token_pattern": r"\b[a-z]+_[a-z0-9_]+\b",
        "ui_icon_token_pattern": r"(corporate_fare|bar_chart|home_pin|location_on|travel_explore|business_center|storefront|schedule|payments|school|work)(?=[A-Z]|\b)|place(?=[A-Z])",
        "script_noise_pattern": r"\b(?:imageloader|document\.getelementbyid|fallback-image)\b",
        "promo_only_title_pattern": r"^(?:[-–—]?\s*)?(?:\d{1,3}%\s*(?:off)?|sale|new(?:\s+in)?|view\s*\d+|best seller|top seller)\s*$",
    },
    "discovered_field_cleanup": {
        "field_noise_tokens": [
            "review",
            "reviews",
            "reviewer",
            "rating",
            "ratings",
            "votes",
            "vote",
            "stars",
            "star",
            "helpful",
            "report",
            "distribution",
            "verified",
            "language",
            "incentives",
            "submission",
        ],
        "value_noise_phrases": [
            "verified reviewer",
            "was this helpful",
            "recommend this product",
            "review this product",
            "filter reviews",
            "rating distribution",
            "overall rating",
            "out of 5",
            "too small",
            "too big",
            "runs very narrow",
            "runs very wide",
            "report this review",
            "reviews with",
            "select to rate",
        ],
    },
    "semantic_detail": {
        "section_skip_patterns": [
            "add to cart",
            "buy now",
            "checkout",
            "login",
            "sign in",
            "subscribe",
            "review this product",
            "filter reviews",
            "rating distribution",
            "overall rating",
            "verified reviewer",
            "read the story",
            "shop women",
            "shop men's",
            "shop mens",
            "shop men",
        ],
        "section_ancestor_stop_tags": ["footer", "header", "nav", "aside", "form"],
        "section_ancestor_stop_tokens": [
            "footer",
            "header",
            "nav",
            "menu",
            "newsletter",
            "breadcrumbs",
            "breadcrumb",
            "cookie",
            "consent",
            "bazaarvoice",
            "bv-rnr",
            "review",
            "reviews",
            "ratings",
        ],
        "spec_label_block_patterns": [
            "play video",
            "watch video",
            "video",
            "learn more",
            "add to cart",
            "buy now",
            "primary guide",
            "guide",
            "discount",
            "verified reviewer",
            "rating summary",
            "filter reviews",
            "report",
            "helpful",
        ],
        "spec_drop_labels": [
            "qty",
            "quantity",
            "details",
            "total",
            "subtotal",
            "delivery",
            "shipping",
            "aggregaterating",
            "aggregate_rating",
            "breadcrumblist",
            "breadcrumb_list",
            "organization",
            "webpage",
            "website",
            "imageobject",
            "image_object",
            "listitem",
            "list_item",
            "searchaction",
            "search_action",
            "offer",
            "itemlist",
            "item_list",
            "howto",
            "faqpage",
            "videoobject",
            "video_object",
            "creativework",
            "creative_work",
            "type",
            "@type",
            "@context",
            "you_are_here",
            "breadcrumb",
            "age",
            "language",
            "incentives",
            "verified_reviewer",
            "rating_distribution",
            "overall_rating",
            "review_this_product",
            "filter_reviews",
            "rating_summary",
            "select",
        ],
        "spec_label_drop_country_names": True,
        "feature_section_aliases": [
            "features",
            "feature",
            "highlights",
            "key_features",
            "key features",
        ],
        "dimension_keywords": [
            "width",
            "height",
            "depth",
            "length",
            "diameter",
            "weight",
            "dimensions",
            "size",
            "measurement",
            "measurements",
        ],
        "aggregate_separator": " | ",
    },
    "jsonld_structural_keys": [
        "@type",
        "@context",
        "@id",
        "@graph",
        "@vocab",
        "@list",
        "@set",
    ],
    "jsonld_non_product_block_types": [
        "organization",
        "website",
        "webpage",
        "breadcrumblist",
        "searchaction",
        "sitenavigationelement",
        "imageobject",
        "videoobject",
        "faqpage",
        "howto",
        "person",
        "localbusiness",
        "store",
    ],
    "product_identity_fields": [
        "title",
        "price",
        "sale_price",
        "original_price",
        "brand",
        "description",
        "sku",
        "image_url",
        "additional_images",
        "availability",
        "category",
    ],
    "nested_non_product_keys": [
        "review",
        "reviews",
        "aggregaterating",
        "aggregate_rating",
        "author",
        "publisher",
        "creator",
        "contributor",
        "breadcrumb",
        "breadcrumblist",
        "itemlistelement",
        "potentialaction",
        "mainentityofpage",
    ],
    "jsonld_type_noise": [
        "aggregaterating",
        "aggregate_rating",
        "breadcrumblist",
        "breadcrumb_list",
        "organization",
        "webpage",
        "website",
        "imageobject",
        "image_object",
        "listitem",
        "list_item",
        "searchaction",
        "search_action",
        "offer",
        "itemlist",
        "item_list",
        "howto",
        "faqpage",
        "videoobject",
        "video_object",
        "creativework",
        "creative_work",
        "type",
        "context",
    ],
    "dynamic_field_name_drop_tokens": [
        "arrivals",
        "bag",
        "best",
        "browse",
        "buy",
        "cart",
        "featured",
        "gifts",
        "less",
        "location",
        "menu",
        "more",
        "new",
        "now",
        "recommended",
        "review",
        "reviews",
        "save",
        "sell",
        "seller",
        "shop",
        "shopping",
        "similar",
        "sort",
        "top",
        "trending",
        "vote",
        "votes",
    ],
    "source_ranking": {
        "contract_xpath": 11,
        "contract_regex": 10,
        "adapter": 9,
        "product_detail": 9,
        "network_intercept": 8,
        "hydrated_state": 7,
        "embedded_json": 7,
        "open_graph": 7,
        "next_data": 7,
        "json_ld": 6,
        "microdata": 5,
        "selector": 4,
        "semantic_section": 3,
        "semantic_spec": 3,
        "dom_buy_box": 8,
        "dom": 2,
        "llm_xpath": 1,
    },
    "field_pollution_rules": {
        "title": {
            "reject_phrases": [
                "cookie preferences",
                "privacy policy",
                "sign in",
                "log in",
                "add to cart",
            ],
        },
        "brand": {
            "reject_phrases": [
                "cookie",
                "privacy",
                "sign in",
                "log in",
            ],
        },
        "category": {
            "reject_phrases": [
                "cookie",
                "privacy",
                "sign in",
                "log in",
            ],
        },
        "description": {
            "reject_phrases": [
                "cookie preferences",
                "privacy settings",
                "manage cookies",
            ],
        },
    },
    "listing_extraction": {
        "minimal_visual_fields": ["title", "image_url"],
        "product_signal_fields": [
            "price",
            "sku",
            "brand",
            "rating",
            "description",
            "availability",
            "review_count",
            "category",
            "salary",
            "company",
            "location",
        ],
        "job_signal_fields": [
            "company",
            "location",
            "salary",
            "job_type",
            "posted_date",
            "apply_url",
        ],
        "detail_path_markers": [
            "/product/",
            "/products/",
            "/pdp/",
            "/dp/",
            "/detail/",
            "/p/",
            "/item/",
            "piid=",
            "/job/",
            "/jobs/detail/",
            "/jobs/",
            "/position/",
            "/opening/",
            "/job-detail/",
        ],
        "swatch_container_selectors": [
            "[class*='swatch']",
            "[class*='color-chip']",
            "[class*='color-option']",
            "[data-color]",
            "[aria-label*='color' i]",
        ],
        "image_exclude_tokens": [
            "icon",
            "logo",
            "sprite",
            "badge",
            "favicon",
            "placeholder",
            "vehicle-new",
            "fitment-warning",
        ],
        "color_action_values": [
            "add to cart",
            "add to bag",
            "quick view",
            "quick shop",
            "save",
            "wishlist",
            "add to wishlist",
            "more options",
            "select",
            "choose",
            "buy now",
            "checkout",
            "shop now",
        ],
        "color_action_prefixes": [
            "add to ",
            "select ",
            "choose ",
            "shop ",
            "buy ",
            "view ",
        ],
        "filter_option_keys": [
            "name",
            "value",
            "selected",
            "tooltip",
            "count",
            "sort",
            "showicon",
            "description",
            "displayname",
            "filtertype",
        ],
        "non_listing_path_tokens": [
            "hiring",
            "employers",
            "recruiter",
            "recruiters",
            "postjobs",
            "demo",
            "pricing",
            "brand",
            "brands",
            "shop",
            "store",
            "catalog",
            "search",
            "results",
            "plans",
            "about",
            "aboutus",
            "contact",
            "contactus",
            "privacy",
            "terms",
            "faq",
            "help",
            "support",
            "careers",
            "press",
            "news",
            "blog",
            "legal",
            "sitemap",
        ],
        "hub_path_segments": [
            "brand",
            "brands",
            "browse",
            "catalog",
            "categories",
            "category",
            "collections",
            "clearance",
            "deals",
            "departments",
            "offers",
            "parts",
            "promo",
            "promotions",
            "results",
            "sale",
            "search",
            "shop",
            "store",
        ],
        "weak_metadata_fields": [
            "title",
            "url",
            "image_url",
            "additional_images",
            "publication_date",
            "posted_date",
            "date",
        ],
        "facet_query_keys": [
            "sv",
            "facet",
            "filter",
            "filters",
            "color",
            "size",
            "material",
            "sort",
        ],
        "facet_path_fragments": ["/see-all", "/filter", "/filters", "/facet"],
        "category_path_markers": [
            "products",
            "categories",
            "category",
            "collections",
            "departments",
            "browse",
            "parts",
        ],
    },
    "acquisition_guards": {
        "job_redirect_shell_titles": [
            "GovernmentJobs | City, State, Federal & Public Sector Jobs"
        ],
        "job_redirect_shell_canonical_urls": ["https://www.schooljobs.com/"],
        "job_redirect_shell_headings": ["log in", "sign in to apply"],
        "job_error_page_titles": ["Sorry. The page you requested could not be found."],
        "job_error_page_headings": [
            "sorry. the page you requested could not be found."
        ],
    },
    "listing_noise_filters": {
        "navigation_title_hints": [
            "home",
            "login",
            "log in",
            "sign in",
            "sign up",
            "register",
            "account",
            "contact",
            "contact us",
            "help",
            "support",
            "read more",
            "learn more",
            "view more",
            "view all",
            "shop all",
            "next",
            "previous",
            "prev",
            "back",
            "checkout",
            "cart",
            "basket",
        ],
        "merchandising_title_prefixes": [
            "shop ",
            "discover ",
            "explore ",
            "find your ",
            "save up ",
            "enjoy ",
            "get ",
        ],
        "editorial_title_patterns": [
            r"\bsponsored\b",
            r"\byou are seeing this ad\b",
            r"\bpromoted\b",
            r"\btrending now\b",
        ],
        "alt_text_title_pattern": r"\b(?:worn|wearing|shown|shot|mid-shot|close-up|detail(?:ed)? view|view of|front view|back view)\b",
        "weak_listing_titles": [
            "new",
            "sale",
            "featured",
            "best seller",
            "top seller",
            "top rated",
        ],
    },
}

NORMALIZATION_RULES = {
    "price_fields": ["price", "sale_price", "original_price"],
    "price_regex": r"\d[\d,.]*",
    "salary_fields": [
        "salary",
        "compensation",
        "pay",
        "salary_range",
        "base_salary",
        "pay_range",
        "compensation_range",
    ],
    "salary_range_regex": r"(?:(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__)?\s*\d[\d,.]*[kKmMbB]?\s*(?:[-–—]|to|until)\s*(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__)?\s*\d[\d,.]*[kKmMbB]?\s*(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__)?(?:\s*/\s*[a-zA-Z]+)?|(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__)\s*\d[\d,.]*[kKmMbB]?(?:\s*(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__))?(?:\s*/\s*[a-zA-Z]+)?|\d[\d,.]*[kKmMbB]?(?:\s*(?:__CURRENCY_SYMBOL_CLASS__|__CURRENCY_CODE_ALT__))?(?:\s*/\s*[a-zA-Z]+)?)",
    "currency_codes": [
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BOV",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHE",
        "CHF",
        "CHW",
        "CLF",
        "CLP",
        "CNY",
        "COP",
        "COU",
        "CRC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MXV",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SHP",
        "SLE",
        "SOS",
        "SRD",
        "SSP",
        "STN",
        "SVC",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "USN",
        "UYI",
        "UYU",
        "UYW",
        "UZS",
        "VED",
        "VES",
        "VND",
        "VUV",
        "WST",
        "XAF",
        "XAG",
        "XAU",
        "XBA",
        "XBB",
        "XBC",
        "XBD",
        "XCD",
        "XDR",
        "XOF",
        "XPD",
        "XPF",
        "XPT",
        "XSU",
        "XTS",
        "XUA",
        "XXX",
        "YER",
        "ZAR",
        "ZMW",
        "ZWG",
    ],
    "currency_symbol_map": {"$": "USD", "€": "EUR", "£": "GBP", "¥": "JPY", "₹": "INR"},
    "color_noise_tokens": [
        "rgb(",
        "rgba(",
        "hsl(",
        "var(",
        "background",
        "color:",
        "border:",
        "display:",
        "margin",
        "padding",
        "font-family",
        "font-size",
        "inherit",
    ],
    "size_noise_tokens": [
        "max-width",
        "min-width",
        "vw",
        "vh",
        "sizes=",
        "srcset",
        "rem",
        "em",
        "px",
        "padding",
        "margin",
        "font-size",
        "display:",
        "border:",
        "auto",
    ],
    "page_url_currency_hints": {
        "/us/": "USD",
        "/en-us/": "USD",
        "/gb/": "GBP",
        "/uk/": "GBP",
        "/en-gb/": "GBP",
        "/ca/": "CAD",
        "/en-ca/": "CAD",
        "/au/": "AUD",
        "/en-au/": "AUD",
        "/eu/": "EUR",
        "/de/": "EUR",
        "/fr/": "EUR",
        "/es/": "EUR",
        "/it/": "EUR",
        "/nl/": "EUR",
        "/in/": "INR",
        "/en-in/": "INR",
        "/jp/": "JPY",
        "/ja-jp/": "JPY",
    },
    "nested_object_keys": {
        "text_fields": [
            "name",
            "label",
            "title",
            "text",
            "value",
            "content",
            "description",
            "alt",
        ],
        "url_fields": ["href", "url", "link", "canonical_url"],
        "price_fields": [
            "specialValue",
            "currentValue",
            "special",
            "current",
            "price",
            "amount",
            "value",
            "lowPrice",
            "minPrice",
            "displayPrice",
            "formattedPrice",
        ],
        "original_price_fields": [
            "compareAtPrice",
            "compare_at_price",
            "listPrice",
            "regularPrice",
            "wasPrice",
            "originalPrice",
            "maxPrice",
            "currentValue",
            "price",
        ],
        "currency_fields": [
            "currency",
            "currencyCode",
            "priceCurrency",
            "currency_code",
        ],
        "category_fields": ["name", "path", "pathEn", "breadcrumb", "categoryPath"],
    },
}

VERDICT_RULES = {
    "detail_core_fields": ["title", "price", "brand"],
    "listing_core_fields": ["title"],
}

HYDRATED_STATE_PATTERNS = [
    "__INITIAL_STATE__",
    "__NUXT__",
    "__APOLLO_STATE__",
    "__PRELOADED_STATE__",
    "__INITIAL_PROPS__",
    "__DATA__",
    "__myx",
    "__STORE__",
    "__APP_STATE__",
]

LLM_TUNING = {
    "html_snippet_max_chars": 12000,
    "existing_values_max_chars": 2400,
    "candidate_evidence_max_chars": 16000,
    "discovered_sources_max_chars": 15000,
    "clean_candidate_text_limit": 1200,
    "groq_max_tokens": 1200,
    "groq_temperature": 0.1,
    "anthropic_max_tokens": 3000,
    "anthropic_temperature": 0.1,
    "nvidia_max_tokens": 1200,
    "nvidia_temperature": 0.1,
}

COOKIE_POLICY = {
    "persist_session_cookies": False,
    "max_persisted_ttl_seconds": 2592000,
    "blocked_name_prefixes": [
        "cf_",
        "__cf",
        "ak_",
        "bm_",
        "dd_",
        "datadome",
        "px",
        "_px",
        "kpsdk",
        "captcha",
    ],
    "blocked_name_contains": [
        "challenge",
        "captcha",
        "datadome",
        "perimeterx",
        "incap",
        "kasada",
        "bot",
    ],
    "harvest_cookie_names": [],
    "harvest_name_prefixes": [],
    "harvest_name_contains": [],
    "blocked_rules_precede_harvest": True,
    "reuse_in_http_client": True,
    "domain_overrides": {
        "your-domain.com": {
            "allowed_cookie_names": ["consent_state", "locale", "currency"],
            "harvest_cookie_names": [],
        }
    },
    "template": True,
    "note": "Replace your-domain.com with the real production domain(s) before enabling domain-specific cookie overrides. blocked_name_prefixes and blocked_name_contains always take precedence over harvest_* rules.",
}

PLATFORM_FAMILIES = {
    "domain_rules": {
        "icims": ["icims.com"],
        "adp": ["workforcenow.adp.com", "myjobs.adp.com", "recruiting.adp.com"],
        "oracle_hcm": ["fa.ocs.oraclecloud.com"],
        "paycom": ["paycomonline.net"],
        "ultipro_ukg": ["recruiting.ultipro.com"],
        "greenhouse": ["boards.greenhouse.io", "boards-api.greenhouse.io"],
    },
    "url_contains_rules": {
        "icims": ["/jobs/search", "/jobs/", "/ajax/joblisting/"],
        "adp": ["/recruitment/recruitment.html", "/srccar/public/", "/srccsh/public/"],
        "oracle_hcm": ["/hcmui/candidateexperience/", "/sites/cx_"],
        "paycom": ["/ats/web.php/portal/", "/career-page"],
        "ultipro_ukg": ["/jobboard/"],
        "greenhouse": ["/embed/job_board", "/jobs/"],
    },
    "html_contains_rules": {
        "icims": ["icims_jobstable", "icims_mainwrapper", "/ajax/joblisting/"],
        "adp": [
            "myjobs.adp.com",
            "recruitment/recruitment.html",
            "workforcenow.adp.com",
        ],
        "oracle_hcm": ["oraclecloud.com", "candidateexperience"],
        "paycom": ["paycomonline.net", "career-page"],
        "ultipro_ukg": ["recruiting.ultipro.com"],
        "greenhouse": ["boards.greenhouse.io", "grnhse_app"],
    },
    "generic_rules": {
        "jobs_url_tokens": [
            "/jobs",
            "/careers",
            "/career",
            "job-search",
            "jobboard",
            "recruitment",
            "currentopenings",
        ],
        "commerce_url_tokens": [
            "/product",
            "/product/",
            "/products/",
            "/shop/",
            "/collections/",
        ],
    },
}

PLATFORM_BROWSER_POLICIES = {
    "browser_first": ["adp"],
}

KNOWN_ATS_PLATFORMS = sorted(
    {
        str(pattern or "").strip().lower()
        for family in PLATFORM_FAMILIES.get("domain_rules", {}).keys()
        for pattern in PLATFORM_FAMILIES.get("domain_rules", {}).get(family, [])
        if str(pattern or "").strip()
    }
)
