from __future__ import annotations

from pathlib import Path

from app.services.config._export_data import load_export_data
from app.services.config.runtime_settings import crawler_runtime_settings

_EXPORTS = load_export_data(str(Path(__file__).with_name("extraction_rules.exports.json")))

ACQUISITION_GUARDS_RULES = _EXPORTS['ACQUISITION_GUARDS_RULES']
ACTION_ADD_TO_CART = _EXPORTS['ACTION_ADD_TO_CART']
ACTION_BUY_NOW = _EXPORTS['ACTION_BUY_NOW']
ACTION_SIGN_IN = _EXPORTS['ACTION_SIGN_IN']
BELK_BRAND_SELECTORS = _EXPORTS['BELK_BRAND_SELECTORS']
BELK_CARD_TITLE_ATTRS = _EXPORTS['BELK_CARD_TITLE_ATTRS']
BELK_IMAGE_SELECTORS = _EXPORTS['BELK_IMAGE_SELECTORS']
BELK_PRICE_SELECTORS = _EXPORTS['BELK_PRICE_SELECTORS']
BELK_PRODUCT_BRAND_KEYS = _EXPORTS['BELK_PRODUCT_BRAND_KEYS']
BELK_PRODUCT_CARD_SELECTORS = _EXPORTS['BELK_PRODUCT_CARD_SELECTORS']
BELK_PRODUCT_ID_KEYS = _EXPORTS['BELK_PRODUCT_ID_KEYS']
BELK_PRODUCT_IMAGE_KEYS = _EXPORTS['BELK_PRODUCT_IMAGE_KEYS']
BELK_PRODUCT_ORIGINAL_PRICE_KEYS = _EXPORTS['BELK_PRODUCT_ORIGINAL_PRICE_KEYS']
BELK_PRODUCT_PRICE_KEYS = _EXPORTS['BELK_PRODUCT_PRICE_KEYS']
BELK_PRODUCT_TITLE_KEYS = _EXPORTS['BELK_PRODUCT_TITLE_KEYS']
BELK_PRODUCT_URL_KEYS = _EXPORTS['BELK_PRODUCT_URL_KEYS']
BELK_TITLE_MAX_CHARS = _EXPORTS['BELK_TITLE_MAX_CHARS']
BELK_TITLE_MIN_CHARS = _EXPORTS['BELK_TITLE_MIN_CHARS']
BELK_TITLE_SELECTORS = _EXPORTS['BELK_TITLE_SELECTORS']
BROWSER_DETAIL_EXPAND_KEYWORDS = _EXPORTS['BROWSER_DETAIL_EXPAND_KEYWORDS']
BROWSER_DETAIL_READINESS_HINTS = _EXPORTS['BROWSER_DETAIL_READINESS_HINTS']
CANDIDATE_ALPHA_CHAR_PATTERN = _EXPORTS['CANDIDATE_ALPHA_CHAR_PATTERN']
CANDIDATE_ANALYTICS_DIMENSION_TOKEN_PATTERN = _EXPORTS['CANDIDATE_ANALYTICS_DIMENSION_TOKEN_PATTERN']
CANDIDATE_ASSET_FILE_EXTENSIONS = _EXPORTS['CANDIDATE_ASSET_FILE_EXTENSIONS']
CANDIDATE_AVAILABILITY_NOISE_PHRASES = _EXPORTS['CANDIDATE_AVAILABILITY_NOISE_PHRASES']
CANDIDATE_AVAILABILITY_TOKENS = _EXPORTS['CANDIDATE_AVAILABILITY_TOKENS']
CANDIDATE_AVAILABILITY_TOKENS_IN_STOCK = _EXPORTS['CANDIDATE_AVAILABILITY_TOKENS_IN_STOCK']
CANDIDATE_AVAILABILITY_TOKENS_LIMITED_STOCK = _EXPORTS['CANDIDATE_AVAILABILITY_TOKENS_LIMITED_STOCK']
CANDIDATE_AVAILABILITY_TOKENS_OUT_OF_STOCK = _EXPORTS['CANDIDATE_AVAILABILITY_TOKENS_OUT_OF_STOCK']
CANDIDATE_AVAILABILITY_TOKENS_PREORDER = _EXPORTS['CANDIDATE_AVAILABILITY_TOKENS_PREORDER']
CANDIDATE_CATEGORY_NOISE_PHRASES = _EXPORTS['CANDIDATE_CATEGORY_NOISE_PHRASES']
CANDIDATE_CATEGORY_TOKENS = _EXPORTS['CANDIDATE_CATEGORY_TOKENS']
CANDIDATE_COLOR_CSS_NOISE_TOKENS = _EXPORTS['CANDIDATE_COLOR_CSS_NOISE_TOKENS']
CANDIDATE_COLOR_VARIANT_COUNT_PATTERN = _EXPORTS['CANDIDATE_COLOR_VARIANT_COUNT_PATTERN']
CANDIDATE_CURRENCY_TOKENS = _EXPORTS['CANDIDATE_CURRENCY_TOKENS']
CANDIDATE_DEEP_ALIAS_LIST_SCAN_LIMIT = _EXPORTS['CANDIDATE_DEEP_ALIAS_LIST_SCAN_LIMIT']
CANDIDATE_DESCRIPTION_FALLBACK_CONTENT_SELECTORS = _EXPORTS['CANDIDATE_DESCRIPTION_FALLBACK_CONTENT_SELECTORS']
CANDIDATE_DESCRIPTION_META_SELECTORS = _EXPORTS['CANDIDATE_DESCRIPTION_META_SELECTORS']
CANDIDATE_DESCRIPTION_TOKENS = _EXPORTS['CANDIDATE_DESCRIPTION_TOKENS']
CANDIDATE_DYNAMIC_FIELD_NAME_HARD_REJECTS = _EXPORTS['CANDIDATE_DYNAMIC_FIELD_NAME_HARD_REJECTS']
CANDIDATE_DYNAMIC_FIELD_NAME_PATTERN = _EXPORTS['CANDIDATE_DYNAMIC_FIELD_NAME_PATTERN']
CANDIDATE_DYNAMIC_NUMERIC_FIELD_PATTERN = _EXPORTS['CANDIDATE_DYNAMIC_NUMERIC_FIELD_PATTERN']
CANDIDATE_FIELD_GROUPS = _EXPORTS['CANDIDATE_FIELD_GROUPS']
CANDIDATE_GENERIC_CATEGORY_VALUES = _EXPORTS['CANDIDATE_GENERIC_CATEGORY_VALUES']
CANDIDATE_GENERIC_TITLE_VALUES = _EXPORTS['CANDIDATE_GENERIC_TITLE_VALUES']
CANDIDATE_IDENTIFIER_TOKENS = _EXPORTS['CANDIDATE_IDENTIFIER_TOKENS']
CANDIDATE_IMAGE_CANDIDATE_DICT_KEYS = _EXPORTS['CANDIDATE_IMAGE_CANDIDATE_DICT_KEYS']
CANDIDATE_IMAGE_COLLECTION_TOKENS = _EXPORTS['CANDIDATE_IMAGE_COLLECTION_TOKENS']
CANDIDATE_IMAGE_FILE_EXTENSIONS = _EXPORTS['CANDIDATE_IMAGE_FILE_EXTENSIONS']
CANDIDATE_IMAGE_NOISE_TOKENS = _EXPORTS['CANDIDATE_IMAGE_NOISE_TOKENS']
CANDIDATE_IMAGE_TOKENS = _EXPORTS['CANDIDATE_IMAGE_TOKENS']
CANDIDATE_IMAGE_URL_HINT_TOKENS = _EXPORTS['CANDIDATE_IMAGE_URL_HINT_TOKENS']
CANDIDATE_NESTED_COLLECTION_SCAN_LIMIT = _EXPORTS['CANDIDATE_NESTED_COLLECTION_SCAN_LIMIT']
CANDIDATE_NOISY_PRODUCT_ATTRIBUTE_KEY_TOKENS = _EXPORTS['CANDIDATE_NOISY_PRODUCT_ATTRIBUTE_KEY_TOKENS']
CANDIDATE_NON_CONTENT_RICH_TEXT_TAGS = _EXPORTS['CANDIDATE_NON_CONTENT_RICH_TEXT_TAGS']
CANDIDATE_PLACEHOLDER_VALUES = _EXPORTS['CANDIDATE_PLACEHOLDER_VALUES']
CANDIDATE_PRICE_TOKENS = _EXPORTS['CANDIDATE_PRICE_TOKENS']
CANDIDATE_PRODUCT_ATTRIBUTE_CSS_NOISE_PATTERN = _EXPORTS['CANDIDATE_PRODUCT_ATTRIBUTE_CSS_NOISE_PATTERN']
CANDIDATE_PRODUCT_ATTRIBUTE_DIGIT_ONLY_KEY_PATTERN = _EXPORTS['CANDIDATE_PRODUCT_ATTRIBUTE_DIGIT_ONLY_KEY_PATTERN']
CANDIDATE_PROMO_ONLY_TITLE_PATTERN = _EXPORTS['CANDIDATE_PROMO_ONLY_TITLE_PATTERN']
CANDIDATE_RATING_TOKENS = _EXPORTS['CANDIDATE_RATING_TOKENS']
CANDIDATE_RATING_WORD_TOKENS = _EXPORTS['CANDIDATE_RATING_WORD_TOKENS']
CANDIDATE_REVIEW_COUNT_TOKENS = _EXPORTS['CANDIDATE_REVIEW_COUNT_TOKENS']
CANDIDATE_SALARY_TOKENS = _EXPORTS['CANDIDATE_SALARY_TOKENS']
CANDIDATE_SCRIPT_NOISE_PATTERN = _EXPORTS['CANDIDATE_SCRIPT_NOISE_PATTERN']
CANDIDATE_SIZE_CSS_NOISE_TOKENS = _EXPORTS['CANDIDATE_SIZE_CSS_NOISE_TOKENS']
CANDIDATE_SIZE_PACKAGE_TOKENS = _EXPORTS['CANDIDATE_SIZE_PACKAGE_TOKENS']
CANDIDATE_TITLE_NOISE_PHRASES = _EXPORTS['CANDIDATE_TITLE_NOISE_PHRASES']
CANDIDATE_TRACKING_PARAM_EXACT_KEYS = _EXPORTS['CANDIDATE_TRACKING_PARAM_EXACT_KEYS']
CANDIDATE_TRACKING_PARAM_PREFIXES = _EXPORTS['CANDIDATE_TRACKING_PARAM_PREFIXES']
CANDIDATE_UI_ICON_TOKEN_PATTERN = _EXPORTS['CANDIDATE_UI_ICON_TOKEN_PATTERN']
CANDIDATE_UI_NOISE_PHRASES = _EXPORTS['CANDIDATE_UI_NOISE_PHRASES']
CANDIDATE_UI_NOISE_TOKEN_PATTERN = _EXPORTS['CANDIDATE_UI_NOISE_TOKEN_PATTERN']
CANDIDATE_URL_ABSOLUTE_PREFIXES = _EXPORTS['CANDIDATE_URL_ABSOLUTE_PREFIXES']
CANDIDATE_URL_ALLOWED_SCHEMES = _EXPORTS['CANDIDATE_URL_ALLOWED_SCHEMES']
CANDIDATE_URL_SUFFIXES = _EXPORTS['CANDIDATE_URL_SUFFIXES']
COLOR_NOISE_TOKENS = _EXPORTS['COLOR_NOISE_TOKENS']
COMMERCE_FIELD_HINTS = _EXPORTS['COMMERCE_FIELD_HINTS']
CROSS_LINK_CONTAINER_HINTS = _EXPORTS['CROSS_LINK_CONTAINER_HINTS']
CSS_NOISE_PATTERN = _EXPORTS['CSS_NOISE_PATTERN']
CSS_NOISE_TOKENS = _EXPORTS['CSS_NOISE_TOKENS']
CURRENCY_CODES = _EXPORTS['CURRENCY_CODES']
CURRENCY_SYMBOL_MAP = _EXPORTS['CURRENCY_SYMBOL_MAP']
DETAIL_BLOCKED_TOKENS = _EXPORTS['DETAIL_BLOCKED_TOKENS']
DETAIL_BRAND_SHELL_DESCRIPTION_PHRASES = _EXPORTS['DETAIL_BRAND_SHELL_DESCRIPTION_PHRASES']
DETAIL_BRAND_SHELL_TITLE_TOKENS = _EXPORTS['DETAIL_BRAND_SHELL_TITLE_TOKENS']
DETAIL_COLLECTION_PATH_TOKENS = _EXPORTS['DETAIL_COLLECTION_PATH_TOKENS']
DETAIL_CURRENT_PRICE_SELECTORS = _EXPORTS['DETAIL_CURRENT_PRICE_SELECTORS']
DETAIL_EXPAND_KEYWORD_EXTENSIONS = _EXPORTS['DETAIL_EXPAND_KEYWORD_EXTENSIONS']
DETAIL_EXPAND_SELECTORS = _EXPORTS['DETAIL_EXPAND_SELECTORS']
DETAIL_IRRELEVANT_JSON_LD_TYPES = _EXPORTS['DETAIL_IRRELEVANT_JSON_LD_TYPES']
DETAIL_NON_PAGE_FILE_EXTENSIONS = _EXPORTS['DETAIL_NON_PAGE_FILE_EXTENSIONS']
DETAIL_ORIGINAL_PRICE_SELECTORS = _EXPORTS['DETAIL_ORIGINAL_PRICE_SELECTORS']
DETAIL_PRODUCT_PATH_TOKENS = _EXPORTS['DETAIL_PRODUCT_PATH_TOKENS']
DETAIL_TITLE_SOURCE_RANKS = _EXPORTS['DETAIL_TITLE_SOURCE_RANKS']
DETAIL_UTILITY_PATH_TOKENS = _EXPORTS['DETAIL_UTILITY_PATH_TOKENS']
DIMENSION_KEYWORDS = _EXPORTS['DIMENSION_KEYWORDS']
DISCOVERED_FIELD_NOISE_TOKENS = _EXPORTS['DISCOVERED_FIELD_NOISE_TOKENS']
DISCOVERED_SOURCE_NOISE_TOKENS = _EXPORTS['DISCOVERED_SOURCE_NOISE_TOKENS']
DISCOVERED_VALUE_NOISE_PHRASES = _EXPORTS['DISCOVERED_VALUE_NOISE_PHRASES']
DISCOVERIST_SCHEMA = _EXPORTS['DISCOVERIST_SCHEMA']
DYNAMIC_FIELD_NAME_DROP_TOKENS = _EXPORTS['DYNAMIC_FIELD_NAME_DROP_TOKENS']
DYNAMIC_FIELD_NAME_SCHEMA_NOISE_REGEXES = _EXPORTS['DYNAMIC_FIELD_NAME_SCHEMA_NOISE_REGEXES']
DYNAMIC_FIELD_NAME_TICKERLIKE_BLOCKLIST = _EXPORTS['DYNAMIC_FIELD_NAME_TICKERLIKE_BLOCKLIST']
EMPTY_SENTINEL_VALUES = _EXPORTS['EMPTY_SENTINEL_VALUES']
EXTRACTION_RULES = _EXPORTS['EXTRACTION_RULES']
FEATURE_SECTION_ALIASES = _EXPORTS['FEATURE_SECTION_ALIASES']
FIELD_POLLUTION_RULES = _EXPORTS['FIELD_POLLUTION_RULES']
FIELD_VALUE_NOISE_FRAGMENTS = _EXPORTS['FIELD_VALUE_NOISE_FRAGMENTS']
GA_DATA_LAYER_KEYS = _EXPORTS['GA_DATA_LAYER_KEYS']
HTTP_URL_PREFIXES = _EXPORTS['HTTP_URL_PREFIXES']
HYDRATED_STATE_PATTERNS = _EXPORTS['HYDRATED_STATE_PATTERNS']
INTEGRAL_PRICE_PAYLOAD_HINT_FIELDS = _EXPORTS['INTEGRAL_PRICE_PAYLOAD_HINT_FIELDS']
INTEGRAL_PRICE_PAYLOAD_VARIANT_FIELDS = _EXPORTS['INTEGRAL_PRICE_PAYLOAD_VARIANT_FIELDS']
JOB_ERROR_PAGE_HEADINGS = _EXPORTS['JOB_ERROR_PAGE_HEADINGS']
JOB_ERROR_PAGE_TITLES = _EXPORTS['JOB_ERROR_PAGE_TITLES']
JOB_FIELD_HINTS = _EXPORTS['JOB_FIELD_HINTS']
JOB_LISTING_DETAIL_PATH_MARKERS = _EXPORTS['JOB_LISTING_DETAIL_PATH_MARKERS']
JOB_REDIRECT_SHELL_CANONICAL_URLS = _EXPORTS['JOB_REDIRECT_SHELL_CANONICAL_URLS']
JOB_REDIRECT_SHELL_HEADINGS = _EXPORTS['JOB_REDIRECT_SHELL_HEADINGS']
JOB_REDIRECT_SHELL_TITLES = _EXPORTS['JOB_REDIRECT_SHELL_TITLES']
JOB_UTILITY_URL_TOKENS = _EXPORTS['JOB_UTILITY_URL_TOKENS']
JSONLD_NON_PRODUCT_BLOCK_TYPES = _EXPORTS['JSONLD_NON_PRODUCT_BLOCK_TYPES']
JSONLD_STRUCTURAL_KEYS = _EXPORTS['JSONLD_STRUCTURAL_KEYS']
JSONLD_TYPE_NOISE = _EXPORTS['JSONLD_TYPE_NOISE']
JS_STATE_NON_PRODUCT_IMAGE_HINTS = _EXPORTS['JS_STATE_NON_PRODUCT_IMAGE_HINTS']
LISTING_ACTION_NOISE_PATTERNS = _EXPORTS['LISTING_ACTION_NOISE_PATTERNS']
LISTING_ALT_TEXT_TITLE_PATTERN = _EXPORTS['LISTING_ALT_TEXT_TITLE_PATTERN']
LISTING_BRAND_MAX_WORDS = _EXPORTS['LISTING_BRAND_MAX_WORDS']
LISTING_BRAND_SELECTORS = _EXPORTS['LISTING_BRAND_SELECTORS']
LISTING_BUY_BOX_AVAILABILITY_PATTERN = _EXPORTS['LISTING_BUY_BOX_AVAILABILITY_PATTERN']
LISTING_BUY_BOX_CURRENCY_SYMBOL_MAP = _EXPORTS['LISTING_BUY_BOX_CURRENCY_SYMBOL_MAP']
LISTING_BUY_BOX_HEADING_SCAN_TAGS = _EXPORTS['LISTING_BUY_BOX_HEADING_SCAN_TAGS']
LISTING_BUY_BOX_HEADING_TEXTS = _EXPORTS['LISTING_BUY_BOX_HEADING_TEXTS']
LISTING_BUY_BOX_PACK_SIZE_PATTERN = _EXPORTS['LISTING_BUY_BOX_PACK_SIZE_PATTERN']
LISTING_BUY_BOX_PRICE_PATTERN = _EXPORTS['LISTING_BUY_BOX_PRICE_PATTERN']
LISTING_BUY_BOX_REQUIRED_TOKENS = _EXPORTS['LISTING_BUY_BOX_REQUIRED_TOKENS']
LISTING_BUY_BOX_SKU_PATTERN = _EXPORTS['LISTING_BUY_BOX_SKU_PATTERN']
LISTING_CARD_TITLE_SELECTORS = _EXPORTS['LISTING_CARD_TITLE_SELECTORS']
LISTING_CARE_SECTION_LABEL = _EXPORTS['LISTING_CARE_SECTION_LABEL']
LISTING_CATEGORY_PATH_MARKERS = _EXPORTS['LISTING_CATEGORY_PATH_MARKERS']
LISTING_COLOR_ACTION_PREFIXES = _EXPORTS['LISTING_COLOR_ACTION_PREFIXES']
LISTING_COLOR_ACTION_VALUES = _EXPORTS['LISTING_COLOR_ACTION_VALUES']
LISTING_DESCRIPTION_CANDIDATE_FIELDS = _EXPORTS['LISTING_DESCRIPTION_CANDIDATE_FIELDS']
LISTING_DETAIL_PATH_MARKERS = _EXPORTS['LISTING_DETAIL_PATH_MARKERS']
LISTING_EDITORIAL_TITLE_PATTERNS = _EXPORTS['LISTING_EDITORIAL_TITLE_PATTERNS']
LISTING_FACET_PATH_FRAGMENTS = _EXPORTS['LISTING_FACET_PATH_FRAGMENTS']
LISTING_FACET_QUERY_KEYS = _EXPORTS['LISTING_FACET_QUERY_KEYS']
LISTING_FALLBACK_CONTAINER_SELECTOR = _EXPORTS['LISTING_FALLBACK_CONTAINER_SELECTOR']
LISTING_FILTER_OPTION_KEYS = _EXPORTS['LISTING_FILTER_OPTION_KEYS']
LISTING_HUB_PATH_SEGMENTS = _EXPORTS['LISTING_HUB_PATH_SEGMENTS']
LISTING_IMAGE_EXCLUDE_TOKENS = _EXPORTS['LISTING_IMAGE_EXCLUDE_TOKENS']
LISTING_JOB_SIGNAL_FIELDS = _EXPORTS['LISTING_JOB_SIGNAL_FIELDS']
LISTING_LABEL_NOISE_TOKENS = _EXPORTS['LISTING_LABEL_NOISE_TOKENS']
LISTING_MATERIALS_SECTION_LABEL = _EXPORTS['LISTING_MATERIALS_SECTION_LABEL']
LISTING_MERCHANDISING_TITLE_PREFIXES = _EXPORTS['LISTING_MERCHANDISING_TITLE_PREFIXES']
LISTING_MINIMAL_VISUAL_FIELDS = _EXPORTS['LISTING_MINIMAL_VISUAL_FIELDS']
LISTING_NAVIGATION_TITLE_HINTS = _EXPORTS['LISTING_NAVIGATION_TITLE_HINTS']
LISTING_NON_LISTING_PATH_TOKENS = _EXPORTS['LISTING_NON_LISTING_PATH_TOKENS']
LISTING_PRODUCT_DETAIL_IMAGE_SOURCE_KEYS = _EXPORTS['LISTING_PRODUCT_DETAIL_IMAGE_SOURCE_KEYS']
LISTING_PRODUCT_DETAIL_LIST_SCAN_LIMIT = _EXPORTS['LISTING_PRODUCT_DETAIL_LIST_SCAN_LIMIT']
LISTING_PRODUCT_DETAIL_PRESENCE_ANY_KEYS = _EXPORTS['LISTING_PRODUCT_DETAIL_PRESENCE_ANY_KEYS']
LISTING_PRODUCT_DETAIL_PRODUCT_BLOB_PATH = _EXPORTS['LISTING_PRODUCT_DETAIL_PRODUCT_BLOB_PATH']
LISTING_PRODUCT_DETAIL_PROPS_PATH = _EXPORTS['LISTING_PRODUCT_DETAIL_PROPS_PATH']
LISTING_PRODUCT_DETAIL_REQUIRED_KEYS = _EXPORTS['LISTING_PRODUCT_DETAIL_REQUIRED_KEYS']
LISTING_PRODUCT_DETAIL_TOP_LEVEL_PAYLOAD_KEYS = _EXPORTS['LISTING_PRODUCT_DETAIL_TOP_LEVEL_PAYLOAD_KEYS']
LISTING_PRODUCT_SIGNAL_FIELDS = _EXPORTS['LISTING_PRODUCT_SIGNAL_FIELDS']
LISTING_STRUCTURED_SPEC_GROUPS_KEY = _EXPORTS['LISTING_STRUCTURED_SPEC_GROUPS_KEY']
LISTING_STRUCTURED_SPEC_GROUP_LIMIT = _EXPORTS['LISTING_STRUCTURED_SPEC_GROUP_LIMIT']
LISTING_STRUCTURED_SPEC_ROW_LIMIT = _EXPORTS['LISTING_STRUCTURED_SPEC_ROW_LIMIT']
LISTING_STRUCTURED_SPEC_SEARCH_MAX_DEPTH = _EXPORTS['LISTING_STRUCTURED_SPEC_SEARCH_MAX_DEPTH']
LISTING_STRUCTURE_NEGATIVE_HINTS = _EXPORTS['LISTING_STRUCTURE_NEGATIVE_HINTS']
LISTING_STRUCTURE_POSITIVE_HINTS = _EXPORTS['LISTING_STRUCTURE_POSITIVE_HINTS']
LISTING_SWATCH_CONTAINER_SELECTORS = _EXPORTS['LISTING_SWATCH_CONTAINER_SELECTORS']
LISTING_TITLE_CTA_TITLES = _EXPORTS['LISTING_TITLE_CTA_TITLES']
LISTING_URL_HINTS = _EXPORTS['LISTING_URL_HINTS']
LISTING_UTILITY_TITLE_PATTERNS = _EXPORTS['LISTING_UTILITY_TITLE_PATTERNS']
LISTING_UTILITY_TITLE_TOKENS = _EXPORTS['LISTING_UTILITY_TITLE_TOKENS']
LISTING_UTILITY_URL_TOKENS = _EXPORTS['LISTING_UTILITY_URL_TOKENS']
LISTING_WEAK_METADATA_FIELDS = _EXPORTS['LISTING_WEAK_METADATA_FIELDS']
LISTING_WEAK_TITLES = _EXPORTS['LISTING_WEAK_TITLES']
LOW_CONTENT_SHELL_PHRASES = _EXPORTS['LOW_CONTENT_SHELL_PHRASES']
LOW_QUALITY_MERGE_TOKENS = _EXPORTS['LOW_QUALITY_MERGE_TOKENS']
MARKDOWN_VIEW = _EXPORTS['MARKDOWN_VIEW']
MAX_SELECTOR_ROWS_PER_FIELD = _EXPORTS['MAX_SELECTOR_ROWS_PER_FIELD']
NESTED_NON_PRODUCT_KEYS = _EXPORTS['NESTED_NON_PRODUCT_KEYS']
NESTED_OBJECT_KEYS_CONFIG = _EXPORTS['NESTED_OBJECT_KEYS_CONFIG']
NETWORK_PAYLOAD_NOISE_URL_PATTERN = _EXPORTS['NETWORK_PAYLOAD_NOISE_URL_PATTERN']
NEXT_FLIGHT_AVAILABILITY_PATTERN = _EXPORTS['NEXT_FLIGHT_AVAILABILITY_PATTERN']
NEXT_FLIGHT_BACK_WINDOW = _EXPORTS['NEXT_FLIGHT_BACK_WINDOW']
NEXT_FLIGHT_BRAND_PATTERNS = _EXPORTS['NEXT_FLIGHT_BRAND_PATTERNS']
NEXT_FLIGHT_FORWARD_WINDOW = _EXPORTS['NEXT_FLIGHT_FORWARD_WINDOW']
NEXT_FLIGHT_ORIGINAL_PRICE_PATTERN = _EXPORTS['NEXT_FLIGHT_ORIGINAL_PRICE_PATTERN']
NEXT_FLIGHT_PAIR_PATTERNS = _EXPORTS['NEXT_FLIGHT_PAIR_PATTERNS']
NEXT_FLIGHT_RATING_PATTERN = _EXPORTS['NEXT_FLIGHT_RATING_PATTERN']
NEXT_FLIGHT_SALE_PRICE_PATTERN = _EXPORTS['NEXT_FLIGHT_SALE_PRICE_PATTERN']
NOISE_CONTAINER_REMOVAL_SELECTOR = _EXPORTS['NOISE_CONTAINER_REMOVAL_SELECTOR']
NOISE_CONTAINER_TOKENS = _EXPORTS['NOISE_CONTAINER_TOKENS']
NOISY_PRODUCT_ATTRIBUTE_KEYS = _EXPORTS['NOISY_PRODUCT_ATTRIBUTE_KEYS']
NOISY_PRODUCT_ATTRIBUTE_LINK_TEXTS = _EXPORTS['NOISY_PRODUCT_ATTRIBUTE_LINK_TEXTS']
NOISY_PRODUCT_ATTRIBUTE_VALUE_PHRASES = _EXPORTS['NOISY_PRODUCT_ATTRIBUTE_VALUE_PHRASES']
NON_PRODUCT_IMAGE_HINTS = _EXPORTS['NON_PRODUCT_IMAGE_HINTS']
NON_PRODUCT_PROVIDER_HINTS = _EXPORTS['NON_PRODUCT_PROVIDER_HINTS']
NORMALIZATION_RULES = _EXPORTS['NORMALIZATION_RULES']
NORMALIZATION_SENTINEL_VALUES = _EXPORTS['NORMALIZATION_SENTINEL_VALUES']
PAGE_URL_CURRENCY_HINTS_RAW = _EXPORTS['PAGE_URL_CURRENCY_HINTS_RAW']
PRICE_FIELDS = _EXPORTS['PRICE_FIELDS']
PRICE_REGEX = _EXPORTS['PRICE_REGEX']
PRODUCT_GALLERY_CONTEXT_HINTS = _EXPORTS['PRODUCT_GALLERY_CONTEXT_HINTS']
PRODUCT_IDENTITY_FIELDS = _EXPORTS['PRODUCT_IDENTITY_FIELDS']
REQUIRED_FIELDS_BY_SURFACE = _EXPORTS['REQUIRED_FIELDS_BY_SURFACE']
REVIEW_CONTAINER_KEYS = _EXPORTS['REVIEW_CONTAINER_KEYS']
SALARY_RANGE_REGEX = _EXPORTS['SALARY_RANGE_REGEX']
SECTION_ANCESTOR_STOP_TAGS = _EXPORTS['SECTION_ANCESTOR_STOP_TAGS']
SECTION_ANCESTOR_STOP_TOKENS = _EXPORTS['SECTION_ANCESTOR_STOP_TOKENS']
SECTION_SKIP_PATTERNS = _EXPORTS['SECTION_SKIP_PATTERNS']
SELECTOR_NOISE_VALUES = _EXPORTS['SELECTOR_NOISE_VALUES']
SEMANTIC_AGGREGATE_SEPARATOR = _EXPORTS['SEMANTIC_AGGREGATE_SEPARATOR']
SEMANTIC_SECTION_NOISE = _EXPORTS['SEMANTIC_SECTION_NOISE']
SIZE_CHART_REGION_KEYS = _EXPORTS['SIZE_CHART_REGION_KEYS']
SIZE_GUIDE_NOISE_VALUES = _EXPORTS['SIZE_GUIDE_NOISE_VALUES']
SIZE_NOISE_TOKENS = _EXPORTS['SIZE_NOISE_TOKENS']
SOCIAL_HOST_SUFFIXES = _EXPORTS['SOCIAL_HOST_SUFFIXES']
SOURCE_PRIORITY = _EXPORTS['SOURCE_PRIORITY']
SOURCE_RANKING = _EXPORTS['SOURCE_RANKING']
SOURCE_TIERS = _EXPORTS['SOURCE_TIERS']
SPEC_DROP_LABELS = _EXPORTS['SPEC_DROP_LABELS']
SPEC_LABEL_BLOCK_PATTERNS = _EXPORTS['SPEC_LABEL_BLOCK_PATTERNS']
SURFACE_WEIGHTS = _EXPORTS['SURFACE_WEIGHTS']
TITLE_NOISE_WORDS = _EXPORTS['TITLE_NOISE_WORDS']
TITLE_PROMOTION_PREFIXES = _EXPORTS['TITLE_PROMOTION_PREFIXES']
TITLE_PROMOTION_SEPARATOR = _EXPORTS['TITLE_PROMOTION_SEPARATOR']
TITLE_PROMOTION_SUBSTRINGS = _EXPORTS['TITLE_PROMOTION_SUBSTRINGS']
VARIANT_AXIS_ALIASES = _EXPORTS['VARIANT_AXIS_ALIASES']
VARIANT_AXIS_LABEL_NOISE_PATTERNS = _EXPORTS['VARIANT_AXIS_LABEL_NOISE_PATTERNS']
VARIANT_AXIS_LABEL_NOISE_TOKENS = _EXPORTS['VARIANT_AXIS_LABEL_NOISE_TOKENS']
VARIANT_CHOICE_GROUP_SELECTOR = _EXPORTS['VARIANT_CHOICE_GROUP_SELECTOR']
VARIANT_COLOR_HINT_WORDS = _EXPORTS['VARIANT_COLOR_HINT_WORDS']
VARIANT_GROUP_ATTR_NOISE_PATTERNS = _EXPORTS['VARIANT_GROUP_ATTR_NOISE_PATTERNS']
VARIANT_GROUP_ATTR_NOISE_TOKENS = _EXPORTS['VARIANT_GROUP_ATTR_NOISE_TOKENS']
VARIANT_SELECT_GROUP_SELECTOR = _EXPORTS['VARIANT_SELECT_GROUP_SELECTOR']
VARIANT_SIZE_VALUE_PATTERNS = _EXPORTS['VARIANT_SIZE_VALUE_PATTERNS']
CURRENCY_ALIAS_PATTERNS = _EXPORTS['CURRENCY_ALIAS_PATTERNS']
HYDRATED_STATE_SCRIPT_IDS = _EXPORTS['HYDRATED_STATE_SCRIPT_IDS']
VARIANT_OPTION_VALUE_SUFFIX_NOISE_PATTERNS = _EXPORTS['VARIANT_OPTION_VALUE_SUFFIX_NOISE_PATTERNS']

DYNAMIC_FIELD_NAME_MAX_TOKENS = crawler_runtime_settings.dynamic_field_name_max_tokens
MAX_CANDIDATES_PER_FIELD = crawler_runtime_settings.max_candidates_per_field

__all__ = sorted(
    [
        'ACQUISITION_GUARDS_RULES',
        'ACTION_ADD_TO_CART',
        'ACTION_BUY_NOW',
        'ACTION_SIGN_IN',
        'BELK_BRAND_SELECTORS',
        'BELK_CARD_TITLE_ATTRS',
        'BELK_IMAGE_SELECTORS',
        'BELK_PRICE_SELECTORS',
        'BELK_PRODUCT_BRAND_KEYS',
        'BELK_PRODUCT_CARD_SELECTORS',
        'BELK_PRODUCT_ID_KEYS',
        'BELK_PRODUCT_IMAGE_KEYS',
        'BELK_PRODUCT_ORIGINAL_PRICE_KEYS',
        'BELK_PRODUCT_PRICE_KEYS',
        'BELK_PRODUCT_TITLE_KEYS',
        'BELK_PRODUCT_URL_KEYS',
        'BELK_TITLE_MAX_CHARS',
        'BELK_TITLE_MIN_CHARS',
        'BELK_TITLE_SELECTORS',
        'BROWSER_DETAIL_EXPAND_KEYWORDS',
        'BROWSER_DETAIL_READINESS_HINTS',
        'CANDIDATE_ALPHA_CHAR_PATTERN',
        'CANDIDATE_ANALYTICS_DIMENSION_TOKEN_PATTERN',
        'CANDIDATE_ASSET_FILE_EXTENSIONS',
        'CANDIDATE_AVAILABILITY_NOISE_PHRASES',
        'CANDIDATE_AVAILABILITY_TOKENS',
        'CANDIDATE_AVAILABILITY_TOKENS_IN_STOCK',
        'CANDIDATE_AVAILABILITY_TOKENS_LIMITED_STOCK',
        'CANDIDATE_AVAILABILITY_TOKENS_OUT_OF_STOCK',
        'CANDIDATE_AVAILABILITY_TOKENS_PREORDER',
        'CANDIDATE_CATEGORY_NOISE_PHRASES',
        'CANDIDATE_CATEGORY_TOKENS',
        'CANDIDATE_COLOR_CSS_NOISE_TOKENS',
        'CANDIDATE_COLOR_VARIANT_COUNT_PATTERN',
        'CANDIDATE_CURRENCY_TOKENS',
        'CANDIDATE_DEEP_ALIAS_LIST_SCAN_LIMIT',
        'CANDIDATE_DESCRIPTION_FALLBACK_CONTENT_SELECTORS',
        'CANDIDATE_DESCRIPTION_META_SELECTORS',
        'CANDIDATE_DESCRIPTION_TOKENS',
        'CANDIDATE_DYNAMIC_FIELD_NAME_HARD_REJECTS',
        'CANDIDATE_DYNAMIC_FIELD_NAME_PATTERN',
        'CANDIDATE_DYNAMIC_NUMERIC_FIELD_PATTERN',
        'CANDIDATE_FIELD_GROUPS',
        'CANDIDATE_GENERIC_CATEGORY_VALUES',
        'CANDIDATE_GENERIC_TITLE_VALUES',
        'CANDIDATE_IDENTIFIER_TOKENS',
        'CANDIDATE_IMAGE_CANDIDATE_DICT_KEYS',
        'CANDIDATE_IMAGE_COLLECTION_TOKENS',
        'CANDIDATE_IMAGE_FILE_EXTENSIONS',
        'CANDIDATE_IMAGE_NOISE_TOKENS',
        'CANDIDATE_IMAGE_TOKENS',
        'CANDIDATE_IMAGE_URL_HINT_TOKENS',
        'CANDIDATE_NESTED_COLLECTION_SCAN_LIMIT',
        'CANDIDATE_NOISY_PRODUCT_ATTRIBUTE_KEY_TOKENS',
        'CANDIDATE_NON_CONTENT_RICH_TEXT_TAGS',
        'CANDIDATE_PLACEHOLDER_VALUES',
        'CANDIDATE_PRICE_TOKENS',
        'CANDIDATE_PRODUCT_ATTRIBUTE_CSS_NOISE_PATTERN',
        'CANDIDATE_PRODUCT_ATTRIBUTE_DIGIT_ONLY_KEY_PATTERN',
        'CANDIDATE_PROMO_ONLY_TITLE_PATTERN',
        'CANDIDATE_RATING_TOKENS',
        'CANDIDATE_RATING_WORD_TOKENS',
        'CANDIDATE_REVIEW_COUNT_TOKENS',
        'CANDIDATE_SALARY_TOKENS',
        'CANDIDATE_SCRIPT_NOISE_PATTERN',
        'CANDIDATE_SIZE_CSS_NOISE_TOKENS',
        'CANDIDATE_SIZE_PACKAGE_TOKENS',
        'CANDIDATE_TITLE_NOISE_PHRASES',
        'CANDIDATE_TRACKING_PARAM_EXACT_KEYS',
        'CANDIDATE_TRACKING_PARAM_PREFIXES',
        'CANDIDATE_UI_ICON_TOKEN_PATTERN',
        'CANDIDATE_UI_NOISE_PHRASES',
        'CANDIDATE_UI_NOISE_TOKEN_PATTERN',
        'CANDIDATE_URL_ABSOLUTE_PREFIXES',
        'CANDIDATE_URL_ALLOWED_SCHEMES',
        'CANDIDATE_URL_SUFFIXES',
        'COLOR_NOISE_TOKENS',
        'COMMERCE_FIELD_HINTS',
        'CROSS_LINK_CONTAINER_HINTS',
        'CSS_NOISE_PATTERN',
        'CSS_NOISE_TOKENS',
        'CURRENCY_CODES',
        'CURRENCY_SYMBOL_MAP',
        'DETAIL_BLOCKED_TOKENS',
        'DETAIL_BRAND_SHELL_DESCRIPTION_PHRASES',
        'DETAIL_BRAND_SHELL_TITLE_TOKENS',
        'DETAIL_COLLECTION_PATH_TOKENS',
        'DETAIL_CURRENT_PRICE_SELECTORS',
        'DETAIL_EXPAND_KEYWORD_EXTENSIONS',
        'DETAIL_EXPAND_SELECTORS',
        'DETAIL_IRRELEVANT_JSON_LD_TYPES',
        'DETAIL_NON_PAGE_FILE_EXTENSIONS',
        'DETAIL_ORIGINAL_PRICE_SELECTORS',
        'DETAIL_PRODUCT_PATH_TOKENS',
        'DETAIL_TITLE_SOURCE_RANKS',
        'DETAIL_UTILITY_PATH_TOKENS',
        'DIMENSION_KEYWORDS',
        'DISCOVERED_FIELD_NOISE_TOKENS',
        'DISCOVERED_SOURCE_NOISE_TOKENS',
        'DISCOVERED_VALUE_NOISE_PHRASES',
        'DISCOVERIST_SCHEMA',
        'DYNAMIC_FIELD_NAME_DROP_TOKENS',
        'DYNAMIC_FIELD_NAME_SCHEMA_NOISE_REGEXES',
        'DYNAMIC_FIELD_NAME_TICKERLIKE_BLOCKLIST',
        'EMPTY_SENTINEL_VALUES',
        'EXTRACTION_RULES',
        'FEATURE_SECTION_ALIASES',
        'FIELD_POLLUTION_RULES',
        'FIELD_VALUE_NOISE_FRAGMENTS',
        'GA_DATA_LAYER_KEYS',
        'HTTP_URL_PREFIXES',
        'HYDRATED_STATE_PATTERNS',
        'INTEGRAL_PRICE_PAYLOAD_HINT_FIELDS',
        'INTEGRAL_PRICE_PAYLOAD_VARIANT_FIELDS',
        'JOB_ERROR_PAGE_HEADINGS',
        'JOB_ERROR_PAGE_TITLES',
        'JOB_FIELD_HINTS',
        'JOB_LISTING_DETAIL_PATH_MARKERS',
        'JOB_REDIRECT_SHELL_CANONICAL_URLS',
        'JOB_REDIRECT_SHELL_HEADINGS',
        'JOB_REDIRECT_SHELL_TITLES',
        'JOB_UTILITY_URL_TOKENS',
        'JSONLD_NON_PRODUCT_BLOCK_TYPES',
        'JSONLD_STRUCTURAL_KEYS',
        'JSONLD_TYPE_NOISE',
        'JS_STATE_NON_PRODUCT_IMAGE_HINTS',
        'LISTING_ACTION_NOISE_PATTERNS',
        'LISTING_ALT_TEXT_TITLE_PATTERN',
        'LISTING_BRAND_MAX_WORDS',
        'LISTING_BRAND_SELECTORS',
        'LISTING_BUY_BOX_AVAILABILITY_PATTERN',
        'LISTING_BUY_BOX_CURRENCY_SYMBOL_MAP',
        'LISTING_BUY_BOX_HEADING_SCAN_TAGS',
        'LISTING_BUY_BOX_HEADING_TEXTS',
        'LISTING_BUY_BOX_PACK_SIZE_PATTERN',
        'LISTING_BUY_BOX_PRICE_PATTERN',
        'LISTING_BUY_BOX_REQUIRED_TOKENS',
        'LISTING_BUY_BOX_SKU_PATTERN',
        'LISTING_CARD_TITLE_SELECTORS',
        'LISTING_CARE_SECTION_LABEL',
        'LISTING_CATEGORY_PATH_MARKERS',
        'LISTING_COLOR_ACTION_PREFIXES',
        'LISTING_COLOR_ACTION_VALUES',
        'LISTING_DESCRIPTION_CANDIDATE_FIELDS',
        'LISTING_DETAIL_PATH_MARKERS',
        'LISTING_EDITORIAL_TITLE_PATTERNS',
        'LISTING_FACET_PATH_FRAGMENTS',
        'LISTING_FACET_QUERY_KEYS',
        'LISTING_FALLBACK_CONTAINER_SELECTOR',
        'LISTING_FILTER_OPTION_KEYS',
        'LISTING_HUB_PATH_SEGMENTS',
        'LISTING_IMAGE_EXCLUDE_TOKENS',
        'LISTING_JOB_SIGNAL_FIELDS',
        'LISTING_LABEL_NOISE_TOKENS',
        'LISTING_MATERIALS_SECTION_LABEL',
        'LISTING_MERCHANDISING_TITLE_PREFIXES',
        'LISTING_MINIMAL_VISUAL_FIELDS',
        'LISTING_NAVIGATION_TITLE_HINTS',
        'LISTING_NON_LISTING_PATH_TOKENS',
        'LISTING_PRODUCT_DETAIL_IMAGE_SOURCE_KEYS',
        'LISTING_PRODUCT_DETAIL_LIST_SCAN_LIMIT',
        'LISTING_PRODUCT_DETAIL_PRESENCE_ANY_KEYS',
        'LISTING_PRODUCT_DETAIL_PRODUCT_BLOB_PATH',
        'LISTING_PRODUCT_DETAIL_PROPS_PATH',
        'LISTING_PRODUCT_DETAIL_REQUIRED_KEYS',
        'LISTING_PRODUCT_DETAIL_TOP_LEVEL_PAYLOAD_KEYS',
        'LISTING_PRODUCT_SIGNAL_FIELDS',
        'LISTING_STRUCTURED_SPEC_GROUPS_KEY',
        'LISTING_STRUCTURED_SPEC_GROUP_LIMIT',
        'LISTING_STRUCTURED_SPEC_ROW_LIMIT',
        'LISTING_STRUCTURED_SPEC_SEARCH_MAX_DEPTH',
        'LISTING_STRUCTURE_NEGATIVE_HINTS',
        'LISTING_STRUCTURE_POSITIVE_HINTS',
        'LISTING_SWATCH_CONTAINER_SELECTORS',
        'LISTING_TITLE_CTA_TITLES',
        'LISTING_URL_HINTS',
        'LISTING_UTILITY_TITLE_PATTERNS',
        'LISTING_UTILITY_TITLE_TOKENS',
        'LISTING_UTILITY_URL_TOKENS',
        'LISTING_WEAK_METADATA_FIELDS',
        'LISTING_WEAK_TITLES',
        'LOW_CONTENT_SHELL_PHRASES',
        'LOW_QUALITY_MERGE_TOKENS',
        'MARKDOWN_VIEW',
        'MAX_SELECTOR_ROWS_PER_FIELD',
        'NESTED_NON_PRODUCT_KEYS',
        'NESTED_OBJECT_KEYS_CONFIG',
        'NETWORK_PAYLOAD_NOISE_URL_PATTERN',
        'NEXT_FLIGHT_AVAILABILITY_PATTERN',
        'NEXT_FLIGHT_BACK_WINDOW',
        'NEXT_FLIGHT_BRAND_PATTERNS',
        'NEXT_FLIGHT_FORWARD_WINDOW',
        'NEXT_FLIGHT_ORIGINAL_PRICE_PATTERN',
        'NEXT_FLIGHT_PAIR_PATTERNS',
        'NEXT_FLIGHT_RATING_PATTERN',
        'NEXT_FLIGHT_SALE_PRICE_PATTERN',
        'NOISE_CONTAINER_REMOVAL_SELECTOR',
        'NOISE_CONTAINER_TOKENS',
        'NOISY_PRODUCT_ATTRIBUTE_KEYS',
        'NOISY_PRODUCT_ATTRIBUTE_LINK_TEXTS',
        'NOISY_PRODUCT_ATTRIBUTE_VALUE_PHRASES',
        'NON_PRODUCT_IMAGE_HINTS',
        'NON_PRODUCT_PROVIDER_HINTS',
        'NORMALIZATION_RULES',
        'NORMALIZATION_SENTINEL_VALUES',
        'PAGE_URL_CURRENCY_HINTS_RAW',
        'PRICE_FIELDS',
        'PRICE_REGEX',
        'PRODUCT_GALLERY_CONTEXT_HINTS',
        'PRODUCT_IDENTITY_FIELDS',
        'REQUIRED_FIELDS_BY_SURFACE',
        'REVIEW_CONTAINER_KEYS',
        'SALARY_RANGE_REGEX',
        'SECTION_ANCESTOR_STOP_TAGS',
        'SECTION_ANCESTOR_STOP_TOKENS',
        'SECTION_SKIP_PATTERNS',
        'SELECTOR_NOISE_VALUES',
        'SEMANTIC_AGGREGATE_SEPARATOR',
        'SEMANTIC_SECTION_NOISE',
        'SIZE_CHART_REGION_KEYS',
        'SIZE_GUIDE_NOISE_VALUES',
        'SIZE_NOISE_TOKENS',
        'SOCIAL_HOST_SUFFIXES',
        'SOURCE_PRIORITY',
        'SOURCE_RANKING',
        'SOURCE_TIERS',
        'SPEC_DROP_LABELS',
        'SPEC_LABEL_BLOCK_PATTERNS',
        'SURFACE_WEIGHTS',
        'TITLE_NOISE_WORDS',
        'TITLE_PROMOTION_PREFIXES',
        'TITLE_PROMOTION_SEPARATOR',
        'TITLE_PROMOTION_SUBSTRINGS',
        'VARIANT_AXIS_ALIASES',
        'VARIANT_AXIS_LABEL_NOISE_PATTERNS',
        'VARIANT_AXIS_LABEL_NOISE_TOKENS',
        'VARIANT_CHOICE_GROUP_SELECTOR',
        'VARIANT_COLOR_HINT_WORDS',
        'VARIANT_GROUP_ATTR_NOISE_PATTERNS',
        'VARIANT_GROUP_ATTR_NOISE_TOKENS',
        'VARIANT_SELECT_GROUP_SELECTOR',
        'VARIANT_SIZE_VALUE_PATTERNS',
        'CURRENCY_ALIAS_PATTERNS',
        'HYDRATED_STATE_SCRIPT_IDS',
        'VARIANT_OPTION_VALUE_SUFFIX_NOISE_PATTERNS',
        "DYNAMIC_FIELD_NAME_MAX_TOKENS",
        "MAX_CANDIDATES_PER_FIELD",
    ]
)
