from __future__ import annotations

from pathlib import Path

from app.services.config._export_data import load_export_data

_EXPORTS = load_export_data(str(Path(__file__).with_name("field_mappings.exports.json")))

CANONICAL_SCHEMAS = _EXPORTS['CANONICAL_SCHEMAS']
COLLECTION_KEYS = _EXPORTS['COLLECTION_KEYS']
DATALAYER_ECOMMERCE_FIELD_MAP = _EXPORTS['DATALAYER_ECOMMERCE_FIELD_MAP']
DOM_HIGH_VALUE_FIELDS = _EXPORTS['DOM_HIGH_VALUE_FIELDS']
DOM_OPTIONAL_CUE_FIELDS = _EXPORTS['DOM_OPTIONAL_CUE_FIELDS']
ECOMMERCE_DETAIL_JS_STATE_FIELDS = _EXPORTS['ECOMMERCE_DETAIL_JS_STATE_FIELDS']
ECOMMERCE_ONLY_FIELDS = _EXPORTS['ECOMMERCE_ONLY_FIELDS']
FIELD_ALIASES = _EXPORTS['FIELD_ALIASES']
INTERNAL_ONLY_FIELDS = _EXPORTS['INTERNAL_ONLY_FIELDS']
JOB_ONLY_FIELDS = _EXPORTS['JOB_ONLY_FIELDS']
PROMPT_REGISTRY = _EXPORTS['PROMPT_REGISTRY']
VARIANT_DOM_FIELD_NAMES = _EXPORTS['VARIANT_DOM_FIELD_NAMES']

__all__ = sorted(
    [
        'CANONICAL_SCHEMAS',
        'COLLECTION_KEYS',
        'DATALAYER_ECOMMERCE_FIELD_MAP',
        'DOM_HIGH_VALUE_FIELDS',
        'DOM_OPTIONAL_CUE_FIELDS',
        'ECOMMERCE_DETAIL_JS_STATE_FIELDS',
        'ECOMMERCE_ONLY_FIELDS',
        'FIELD_ALIASES',
        'INTERNAL_ONLY_FIELDS',
        'JOB_ONLY_FIELDS',
        'PROMPT_REGISTRY',
        'VARIANT_DOM_FIELD_NAMES',
    ]
)
