from __future__ import annotations

from pathlib import Path

from app.services.config._export_data import load_export_data

_EXPORTS = load_export_data(str(Path(__file__).with_name("field_mappings.exports.json")))

CANONICAL_SCHEMAS = _EXPORTS['CANONICAL_SCHEMAS']
COLLECTION_KEYS = _EXPORTS['COLLECTION_KEYS']
DATALAYER_ECOMMERCE_FIELD_MAP = _EXPORTS['DATALAYER_ECOMMERCE_FIELD_MAP']
DOM_HIGH_VALUE_FIELDS = _EXPORTS['DOM_HIGH_VALUE_FIELDS']
DOM_OPTIONAL_CUE_FIELDS = _EXPORTS['DOM_OPTIONAL_CUE_FIELDS']
ECOMMERCE_DETAIL_JS_STATE_FIELDS = _EXPORTS['ECOMMERCE_DETAIL_JS_STATE_FIELDS']
ECOMMERCE_ONLY_FIELDS = _EXPORTS['ECOMMERCE_ONLY_FIELDS']
FIELD_ALIASES = _EXPORTS['FIELD_ALIASES']
INTERNAL_ONLY_FIELDS = _EXPORTS['INTERNAL_ONLY_FIELDS']
JOB_ONLY_FIELDS = _EXPORTS['JOB_ONLY_FIELDS']
PROMPT_REGISTRY = _EXPORTS['PROMPT_REGISTRY']
PUBLIC_RECORD_DEFAULT_EXCLUDED_FIELDS = _EXPORTS.get('PUBLIC_RECORD_DEFAULT_EXCLUDED_FIELDS', {})
PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_KEYS = _EXPORTS['PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_KEYS']
PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_PREFIXES = _EXPORTS['PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_PREFIXES']
VARIANT_DOM_FIELD_NAMES = _EXPORTS['VARIANT_DOM_FIELD_NAMES']

PUBLIC_RECORD_URL_BLOCKED_PATH_MARKERS = (
    "/api/",
    "/event/",
    "/events/",
    "/tracking/",
    "/analytics/",
    "/beacon/",
    "/click",
)
PUBLIC_RECORD_URL_MAX_LENGTH = 2048

__all__ = sorted(
    [
        'CANONICAL_SCHEMAS',
        'COLLECTION_KEYS',
        'DATALAYER_ECOMMERCE_FIELD_MAP',
        'DOM_HIGH_VALUE_FIELDS',
        'DOM_OPTIONAL_CUE_FIELDS',
        'ECOMMERCE_DETAIL_JS_STATE_FIELDS',
        'ECOMMERCE_ONLY_FIELDS',
        'FIELD_ALIASES',
        'INTERNAL_ONLY_FIELDS',
        'JOB_ONLY_FIELDS',
        'PROMPT_REGISTRY',
        'PUBLIC_RECORD_DEFAULT_EXCLUDED_FIELDS',
        'PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_KEYS',
        'PUBLIC_RECORD_DETAIL_CANONICAL_QUERY_PREFIXES',
        'PUBLIC_RECORD_URL_BLOCKED_PATH_MARKERS',
        'PUBLIC_RECORD_URL_MAX_LENGTH',
        'VARIANT_DOM_FIELD_NAMES',
    ]
)
