from __future__ import annotations

CANONICAL_SCHEMAS = {
    "ecommerce_listing": [
        "title",
        "brand",
        "sku",
        "part_number",
        "price",
        "sale_price",
        "original_price",
        "currency",
        "availability",
        "image_url",
        "additional_images",
        "color",
        "size",
        "dimensions",
        "rating",
        "review_count",
        "url",
    ],
    "ecommerce_detail": [
        "title",
        "brand",
        "sku",
        "part_number",
        "price",
        "sale_price",
        "original_price",
        "currency",
        "availability",
        "image_url",
        "additional_images",
        "description",
        "rating",
        "review_count",
        "category",
        "color",
        "size",
        "materials",
        "care",
    ],
    "job_listing": [
        "title",
        "company",
        "location",
        "salary",
        "job_type",
        "posted_date",
        "url",
        "apply_url",
    ],
    "job_detail": [
        "title",
        "company",
        "location",
        "salary",
        "job_type",
        "posted_date",
        "apply_url",
        "description",
        "requirements",
        "responsibilities",
        "qualifications",
        "benefits",
        "skills",
        "remote",
    ],
    "automobile_listing": [
        "title",
        "price",
        "url",
        "image_url",
        "make",
        "model",
        "year",
        "mileage",
        "location",
        "dealer_name",
    ],
    "automobile_detail": [
        "title",
        "price",
        "currency",
        "make",
        "model",
        "year",
        "trim",
        "mileage",
        "vin",
        "condition",
        "body_style",
        "fuel_type",
        "transmission",
        "drivetrain",
        "exterior_color",
        "interior_color",
        "location",
        "dealer_name",
        "image_url",
        "description",
    ],
    "tabular": [],
}

FIELD_ALIASES = {
    "title": ["title", "name", "job_title", "position", "headline", "productName", "product_name"],
    "url": [
        "url",
        "link",
        "href",
        "apply_url",
        "canonical_url",
        "product_url",
        "landingPageUrl",
        "detailPageLink",
        "detail_page_link",
        "workUrl",
        "listingUrl",
        "positionURI",
    ],
    "slug": ["slug"],
    "price": ["price", "amount", "cost", "sale_price", "current_price", "buyNowPrice", "lowPrice"],
    "sale_price": ["sale_price", "saleprice", "sellingprice", "newprice", "discount_price", "discountedPrice"],
    "original_price": [
        "compare_at_price",
        "list_price",
        "regular_price",
        "was_price",
        "original_price",
        "mrp",
        "listPrice",
        "highPrice",
    ],
    "currency": ["currency", "currency_code", "price_currency"],
    "brand": ["brand", "vendor", "manufacturer", "company_name", "brand_name", "designer", "brandName"],
    "image_url": [
        "image",
        "image_url",
        "thumbnail",
        "img",
        "photo",
        "logo",
        "featured_image",
        "primary_image",
        "searchImage",
        "imageUrl",
    ],
    "additional_images": ["images", "gallery", "gallery_images", "product_images", "media", "photos", "assets"],
    "color": ["colors", "color_name", "finish", "frame_color"],
    "size": ["sizes", "variant_size", "dimension_label"],
    "description": ["description", "body", "summary", "snippet", "content", "body_html", "short_description"],
    "company": ["company", "company_name", "companyName", "organization", "employer", "hiring_organization", "agency"],
    "location": ["location", "candidate_required_location", "job_location", "city", "region"],
    "salary": ["salary", "compensation", "pay", "salary_range", "salaryDisplay"],
    "category": ["category", "department", "type", "product_type", "job_type", "employment_type"],
    "sku": ["sku", "product_id", "item_id", "id"],
    "part_number": ["part_number", "part", "part_no", "partNumber", "mpn", "manufacturer_part_number"],
    "availability": ["availability", "in_stock", "stock_status", "inStock"],
    "tags": ["tags", "labels", "keywords"],
    "rating": ["rating", "average_rating", "score", "rating_value", "aggregate_rating"],
    "review_count": ["review_count", "total_reviews", "num_reviews", "numberOfReviews"],
    "publication_date": ["publication_date", "date", "created_at", "posted_at", "published_at", "pub_date", "date_posted"],
    "posted_date": ["posted_date", "date_posted", "publication_date", "posted_at"],
    "apply_url": ["apply_url", "application_url", "job_url", "product_link"],
    "responsibilities": ["responsibilities", "job_requirements", "requirements", "duties", "job_duties", "what_you_ll_do", "what_you_will_do"],
    "qualifications": ["qualifications", "job_qualification", "prerequisites", "minimum_requirements", "preferred_qualifications", "who_you_are"],
    "benefits": ["benefits", "job_benefits", "perks", "compensation_benefits", "what_we_offer"],
    "skills": ["skills", "job_skills", "competencies", "abilities", "experience", "what_you_ll_bring"],
    "remote": ["remote", "work_from_home", "wfh", "telecommute"],
    "specifications": ["specifications", "details", "technical_details", "product_details", "the_details"],
    "features": ["features", "highlights", "key_features"],
    "materials": ["materials", "fabric", "composition", "fabric_content"],
    "care": ["care", "care_instructions", "product_care"],
    "dimensions": ["dimensions", "size", "sizing", "measurements"],
    "summary": ["summary", "overview", "about"],
    "requirements": ["requirements", "job_requirements", "prerequisites"],
    "job_type": ["job_type", "employment_type"],
    "make": ["make", "manufacturer"],
    "model": ["model"],
    "year": ["year"],
    "trim": ["trim"],
    "mileage": ["mileage", "distance"],
    "vin": ["vin"],
    "condition": ["condition"],
    "body_style": ["body_style", "body type"],
    "fuel_type": ["fuel_type", "fuel"],
    "transmission": ["transmission"],
    "drivetrain": ["drivetrain"],
    "exterior_color": ["exterior_color", "color"],
    "interior_color": ["interior_color"],
    "dealer_name": ["dealer_name", "dealer"],
}

COLLECTION_KEYS = [
    "products",
    "items",
    "results",
    "data",
    "records",
    "listings",
    "jobs",
    "job-list",
    "job_list",
    "postings",
    "positions",
    "openings",
    "hits",
    "entries",
    "nodes",
    "drinks",
    "meals",
    "categories",
    "collections",
    "offers",
    "deals",
    "articles",
    "content",
    "users",
    "works",
    "books",
    "movies",
    "shows",
    "tracks",
    "events",
    "properties",
    "features",
    "objects",
    "documents",
    "rows",
    "values",
    "response",
]

REQUESTED_FIELD_ALIASES = {
    "responsibilities": [
        "responsibilities",
        "job responsibilities",
        "key responsibilities",
        "duties",
        "job duties",
        "what you'll do",
        "what you’ll do",
        "what_you_ll_do",
        "what_you_will_do",
        "role responsibilities",
    ],
    "qualifications": [
        "qualifications",
        "job qualifications",
        "job_qualification",
        "prerequisites",
        "minimum requirements",
        "minimum_requirements",
        "preferred qualifications",
        "preferred_qualifications",
        "who you are",
        "what we're looking for",
        "what we’re looking for",
    ],
    "benefits": [
        "benefits",
        "job benefits",
        "job_benefits",
        "perks",
        "why you'll love this job",
        "why you’ll love this job",
        "life at stripe",
        "what we offer",
    ],
    "skills": ["skills", "job skills", "job_skills", "competencies", "abilities", "experience", "what you'll bring", "what you’ll bring"],
    "summary": ["summary", "overview", "about", "description", "our opportunity", "about the role", "about the team"],
    "specifications": ["specifications", "specs", "spec", "details", "technical details", "tech specs", "product details", "the details"],
    "features": ["features", "highlights", "key features"],
    "materials": ["materials", "fabric", "composition", "fabric content"],
    "care": ["care", "care instructions", "product care"],
    "dimensions": ["dimensions", "size", "sizing", "measurements"],
    "remote": ["remote", "work from home", "wfh"],
    "requirements": ["requirements", "job_requirements", "prerequisites"],
}

PROMPT_REGISTRY = {
    "xpath_discovery": {
        "system_file": "xpath_discovery.system.txt",
        "user_file": "xpath_discovery.user.txt",
        "response_type": "object",
        "data_key": "selectors",
    },
    "missing_field_extraction": {
        "system_file": "missing_field_extraction.system.txt",
        "user_file": "missing_field_extraction.user.txt",
        "response_type": "object",
    },
    "field_cleanup_review": {
        "system_file": "field_cleanup_review.system.txt",
        "user_file": "field_cleanup_review.user.txt",
        "response_type": "object",
    },
    "page_classification": {
        "system_file": "page_classification.system.txt",
        "user_file": "page_classification.user.txt",
        "response_type": "object",
    },
    "schema_inference": {
        "system_file": "schema_inference.system.txt",
        "user_file": "schema_inference.user.txt",
        "response_type": "object",
    },
}
