export const CRAWL_DEFAULTS = {
  REQUEST_DELAY_MS: 500,
  MAX_RECORDS: 100,
  MAX_PAGES: 10,
  SCROLL_THRESHOLD_PX: 50,
} as const;

export const CRAWL_LIMITS = {
  MIN_REQUEST_DELAY_MS: 0,
  MAX_REQUEST_DELAY_MS: 5000,
  MIN_RECORDS: 1,
  MAX_RECORDS: 10000,
  MIN_PAGES: 1,
  MAX_PAGES: 500,
} as const;
