from __future__ import annotations

from app.services.acquisition.blocked_detector import detect_blocked_page


def test_detect_blocked_page_empty_html():
    verdict = detect_blocked_page("")

    assert verdict.is_blocked
    assert verdict.reason == "empty_or_too_short"


def test_detect_blocked_page_blocks_perimeterx():
    html = """
    <html>
      <head><title>Access Denied</title></head>
      <body>
        <div class="px-captcha">Please verify you are a human</div>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "perimeterx"


def test_detect_blocked_page_blocks_cloudflare():
    html = """
    <html>
      <head><title>Just a moment</title></head>
      <body>
        <div id="cf-challenge">Checking your browser before accessing example.com.</div>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "cloudflare"


def test_detect_blocked_page_allows_rich_pages_with_dormant_antibot_markup():
    html = """
    <html>
      <head><title>Product Page</title></head>
      <body>
        <div id="dd-modal" hidden></div>
        <main>
          <nav>
            <a href="/one">One</a>
            <a href="/two">Two</a>
            <a href="/three">Three</a>
            <a href="/four">Four</a>
            <a href="/five">Five</a>
          </nav>
          <article>
            <h1>Example Product</h1>
            <p>{content}</p>
          </article>
        </main>
      </body>
    </html>
    """.format(content="useful content " * 300)

    verdict = detect_blocked_page(html)

    assert not verdict.is_blocked


def test_detect_blocked_page_blocks_kasada():
    html = """
    <html>
      <head><title>Access denied</title></head>
      <body>
        <script src="https://example.com/kpsdk.js"></script>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "kasada"


def test_detect_blocked_page_blocks_akamai():
    html = """
    <html>
      <head>
        <title>Access Denied</title>
        <script src="https://static.akamai.example/challenge.js"></script>
      </head>
      <body>
        <p>Access denied.</p>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "akamai"


def test_detect_blocked_page_allows_rich_akamai_tagged_pages_with_real_content():
    html = """
    <html>
      <head>
        <title>Dyson Air Treatment</title>
        <script src="https://www.dyson.in/akam/sw.js"></script>
      </head>
      <body>
        <main>
          <nav>
            <a href="/air-treatment">Air Treatment</a>
            <a href="/purifiers">Purifiers</a>
            <a href="/fans">Fans</a>
            <a href="/filters">Filters</a>
            <a href="/support">Support</a>
          </nav>
          <section>
            <h1>Dyson Purifier Cool</h1>
            <p>{content}</p>
          </section>
        </main>
      </body>
    </html>
    """.format(content="HEPA H13 filtration and coverage details " * 180)

    verdict = detect_blocked_page(html)

    assert not verdict.is_blocked


def test_detect_blocked_page_blocks_active_marker_on_low_content_page():
    html = """
    <html>
      <head><title>Just a moment</title></head>
      <body>
        <div id="dd-modal">Verifying your browser</div>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "datadome"


def test_detect_blocked_page_blocks_chewy_akamai_403_page():
    html = """
    <html>
      <head><title>403 error - No treats beyond this point - Chewy</title></head>
      <body>
        <main>
          <h1>No treats beyond this point</h1>
          <p>You've stumbled upon a page with restricted access.</p>
          <div id="Code">Page error: 403</div>
          <script>window.akamai_ref_error_code = "18.example";</script>
        </main>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "akamai"


def test_detect_blocked_page_blocks_cloudfront_request_blocked_page():
    html = """
    <html>
      <head><title>ERROR: The request could not be satisfied</title></head>
      <body>
        <h1>403 ERROR</h1>
        <h2>The request could not be satisfied.</h2>
        <p>Request blocked.</p>
        <pre>Generated by cloudfront (CloudFront)</pre>
      </body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.provider == "cloudfront"


def test_detect_blocked_page_allows_normal_page():
    html = """
    <html>
      <head><title>Example Product</title></head>
      <body>
        <main>
          <h1>Widget Pro</h1>
          <p>{content}</p>
          <a href="/related">Related products</a>
          <a href="/shipping">Shipping</a>
          <a href="/support">Support</a>
          <a href="/faq">FAQ</a>
          <a href="/reviews">Reviews</a>
        </main>
      </body>
    </html>
    """.format(content="normal product content " * 200)

    verdict = detect_blocked_page(html)

    assert not verdict.is_blocked


def test_detect_blocked_page_large_html_ignores_noscript_and_svg_text():
    html = """
    <html>
      <head><title>Example Product</title></head>
      <body>
        <noscript>request blocked request could not be satisfied generated by cloudfront</noscript>
        <svg><text>access denied</text></svg>
        <main>
          <h1>Widget Pro</h1>
          <p>{content}</p>
          <a href="/related">Related products</a>
          <a href="/shipping">Shipping</a>
          <a href="/support">Support</a>
          <a href="/faq">FAQ</a>
        </main>
      </body>
    </html>
    """.format(content="normal product content " * 6000)

    verdict = detect_blocked_page(html)

    assert not verdict.is_blocked


def test_detect_blocked_page_blocks_short_403_forbidden_page():
    html = """
    <html>
      <head><title>403 Forbidden</title></head>
      <body><h1>403 Forbidden</h1></body>
    </html>
    """

    verdict = detect_blocked_page(html)

    assert verdict.is_blocked
    assert verdict.reason == "blocked_phrase:403_forbidden"
